// SPDX-License-Identifier: GPL-3.0-or-later
//
// leyline_pattern_codebook_test.dart — the Mutable Leyline SUMMON and ARMOR
// dictionary vectors (audit R-8, Slice F; LEYLINE_SEED_PLAN.md §8, §9, §15).
//
// ## Where the expected values come from
//
// `scripts/gen_leyline_pattern_vectors.py`, an INDEPENDENT implementation
// written from the byte layout ruled in R-8 rather than from the Dart. A vector
// generated by running the code under test proves only that the code is
// deterministic; it cannot catch a transcription error, because the error would
// be in both the code and the "expected" value. Every constant below is that
// script's output, transcribed.
//
// Re-run it (`python3 scripts/gen_leyline_pattern_vectors.py`) whenever this
// file's expectations are in question. Changing any of them is a consensus
// change requiring a lexicon-version bump, not a refactor — two devices that
// disagree about whether a creature flies resolve different battles from the
// same certified trajectory.
//
// ## What the vectors pin, beyond the bytes
//
// Three properties R-8 rests on, each of which is a design ruling and not an
// implementation detail:
//
//   1. **Sparse, not half.** Eight of 256 summon patterns and seven of 256
//      armor patterns are meaningful — the ordinary cardinality — NOT the ~50%
//      an incantation codebook uses. Half of all sliding windows meaning
//      something would be a different game.
//   2. **Four, not `formulaLength`.** `rivendell 4`, `rivendell 5` and
//      `rivendell 6` share ONE summon dictionary and ONE armor dictionary, and
//      every pattern in them is four elements long.
//   3. **Three independent dictionaries.** One seed, three domain tags, and
//      knowing any one dictionary tells you nothing about the other two.

import 'package:flutter_test/flutter_test.dart';

import 'package:rune_duel/battle/models/armor_keyword.dart';
import 'package:rune_duel/battle/models/leyline_codebook.dart'
    show IncantationCodebook;
import 'package:rune_duel/battle/models/leyline_config.dart';
import 'package:rune_duel/battle/models/leyline_pattern_codebook.dart';
import 'package:rune_duel/battle/models/leyline_stream.dart';
import 'package:rune_duel/battle/models/summon_ability.dart';
import 'package:rune_duel/engine/border_zone.dart';

// ── Fixtures ──────────────────────────────────────────────────────────────────

LeylineConfig _rivendell({int length = 4, int noise = 500}) =>
    LeylineConfig.mutable(
      communitySeed: 'rivendell',
      formulaLength: length,
      noiseDensityPermille: noise,
    );

LeylineConfig _glassmountain({int length = 4, int noise = 500}) =>
    LeylineConfig.mutable(
      communitySeed: 'glassmountain',
      formulaLength: length,
      noiseDensityPermille: noise,
    );

/// `'EWWE'` -> the four zones. The generator prints patterns this way, so the
/// vectors below can be transcribed exactly as it printed them.
List<BorderZone> _p(String initials) => [
      for (final c in initials.split(''))
        switch (c) {
          'F' => BorderZone.fire,
          'A' => BorderZone.air,
          'W' => BorderZone.water,
          'E' => BorderZone.earth,
          _ => throw ArgumentError('bad initial "$c"'),
        },
    ];

String _s(List<BorderZone> pattern) => pattern.map(summonInitial).join();

LeylinePatternCodebook _summonBook(LeylineConfig config) =>
    LeylinePatternCodebook.derive(
      config: config,
      domainTag: kLeylineSummonDomain,
      outputCodes: [for (final a in SummonAbility.values) summonAbilityCode(a)],
    );

LeylinePatternCodebook _armorBook(LeylineConfig config) =>
    LeylinePatternCodebook.derive(
      config: config,
      domainTag: kLeylineArmorDomain,
      outputCodes: [for (final k in ArmorKeyword.values) armorKeywordCode(k)],
    );

// ── The vectors (gen_leyline_pattern_vectors.py output, transcribed) ──────────

const String _kRivendellTradition =
    'e668209ffe9a8aca95c1c6c0ead4945b1bfb74793739634c7d686a79c90a8524';
const String _kGlassmountainTradition =
    '6cf31ba1f95684b17d480b6b8025292a9284048d9dc6a30096f69a7ae5d1a512';
const String _kOrdinaryDefaultTradition =
    '9d19d5cc8dad72ec211dbb9326a6222e7d40eafdc1f38238e470e521635cd8ec';
const String _kOrdinaryRivendellTradition =
    'd67186d493b8e26946a6f4585ac2682367a15fdb9730acbbf6a2bb0393145e7f';

/// The COMPLETE meaningful set under `rivendell 4`, in derived rank order.
const List<(String, SummonAbility)> _kRivendellSummon = [
  ('EWWE', SummonAbility.stealthy),
  ('WEWF', SummonAbility.flying),
  ('WWWA', SummonAbility.moltenCarapace),
  ('AEAF', SummonAbility.morphic),
  ('WFEA', SummonAbility.big),
  ('EFEA', SummonAbility.charger),
  ('AWEF', SummonAbility.cleave),
  ('WAEA', SummonAbility.muddy),
];

/// The first four INERT patterns, in derived rank order — i.e. the entries just
/// past the meaningful prefix.
const List<String> _kRivendellSummonInert = ['FWWA', 'FWFW', 'AFEF', 'FWWE'];

const List<(String, ArmorKeyword)> _kRivendellArmor = [
  ('EFWA', ArmorKeyword.muddy),
  ('WWEF', ArmorKeyword.flying),
  ('AEEF', ArmorKeyword.cleave),
  ('WEAF', ArmorKeyword.anchored),
  ('EWFF', ArmorKeyword.charger),
  ('WWFA', ArmorKeyword.moltenCarapace),
  ('WFWA', ArmorKeyword.stealthy),
];

const List<String> _kRivendellArmorInert = ['FFWW', 'AEFA', 'FFWE', 'WWAW'];

const List<(String, SummonAbility)> _kGlassmountainSummon = [
  ('AFFW', SummonAbility.big),
  ('FEAA', SummonAbility.cleave),
  ('FFWE', SummonAbility.flying),
  ('WFFW', SummonAbility.muddy),
  ('AFFE', SummonAbility.stealthy),
  ('WAWA', SummonAbility.moltenCarapace),
  ('WAEA', SummonAbility.morphic),
  ('WEEF', SummonAbility.charger),
];

const List<(String, ArmorKeyword)> _kGlassmountainArmor = [
  ('AEEE', ArmorKeyword.muddy),
  ('AFFF', ArmorKeyword.flying),
  ('FAFF', ArmorKeyword.charger),
  ('EEAF', ArmorKeyword.stealthy),
  ('FEEE', ArmorKeyword.moltenCarapace),
  ('WWFA', ArmorKeyword.anchored),
  ('WFFW', ArmorKeyword.cleave),
];

void main() {
  // ── The tradition hash ─────────────────────────────────────────────────────

  group('leylineTraditionHash', () {
    test('pinned vectors', () {
      expect(_rivendell().leylineTraditionHash, _kRivendellTradition);
      expect(_glassmountain().leylineTraditionHash, _kGlassmountainTradition);
      expect(LeylineConfig.ordinaryDefault.leylineTraditionHash,
          _kOrdinaryDefaultTradition);
      expect(LeylineConfig.ordinary('rivendell').leylineTraditionHash,
          _kOrdinaryRivendellTradition);
    });

    test('formulaLength and noise density are NOT bound (R-8)', () {
      // The whole projection, in one assertion. If this ever fails, `rivendell
      // 4` and `rivendell 6` have become two traditions of creatures and armor
      // rather than two grammars of speech.
      for (final other in [
        _rivendell(length: 5),
        _rivendell(length: 6),
        _rivendell(noise: 0),
        _rivendell(noise: 333),
        _rivendell(length: 6, noise: 1),
      ]) {
        expect(other.leylineTraditionHash, _kRivendellTradition);
      }
    });

    test('the seed, the lexicon generation and mutability ARE bound', () {
      expect(_glassmountain().leylineTraditionHash,
          isNot(_rivendell().leylineTraditionHash));
      expect(LeylineConfig.ordinary('rivendell').leylineTraditionHash,
          isNot(_rivendell().leylineTraditionHash));
    });

    test('it is a DIFFERENT hash from the config hash', () {
      // Two hashes of one config under two domain tags. If a refactor ever made
      // these equal, the projection above would be silently gone.
      final config = _rivendell();
      expect(config.leylineTraditionHash, isNot(config.leylineConfigHash));
    });

    test('equivalent spellings are one tradition', () {
      for (final spelling in const [
        'Rivendell',
        'RIVENDELL',
        '  rivendell  ',
        'Rivendell!',
        'ri-ven-dell',
      ]) {
        expect(
          LeylineConfig.mutable(communitySeed: spelling, formulaLength: 4)
              .leylineTraditionHash,
          _kRivendellTradition,
          reason: '"$spelling" must normalize to one tradition',
        );
      }
    });
  });

  // ── The dictionaries ───────────────────────────────────────────────────────

  group('summon dictionary vectors', () {
    test('the complete meaningful set under rivendell 4', () {
      final book = _summonBook(_rivendell());
      expect(book.meaningfulPatternCount, _kRivendellSummon.length);
      for (var rank = 0; rank < _kRivendellSummon.length; rank++) {
        final (initials, ability) = _kRivendellSummon[rank];
        expect(_s(book.orderedPatterns[rank]), initials,
            reason: 'rank $rank of the derived order');
        expect(book.codeFor(_p(initials)), summonAbilityCode(ability));
        expect(_s(book.patternFor(summonAbilityCode(ability))!), initials);
      }
    });

    test('the patterns just past the prefix are inert', () {
      final book = _summonBook(_rivendell());
      for (var i = 0; i < _kRivendellSummonInert.length; i++) {
        final initials = _kRivendellSummonInert[i];
        expect(_s(book.orderedPatterns[_kRivendellSummon.length + i]), initials);
        expect(book.codeFor(_p(initials)), isNull,
            reason: '$initials must name nothing under rivendell 4');
      }
    });

    test('a different seed is a different dictionary', () {
      final book = _summonBook(_glassmountain());
      for (var rank = 0; rank < _kGlassmountainSummon.length; rank++) {
        final (initials, ability) = _kGlassmountainSummon[rank];
        expect(_s(book.orderedPatterns[rank]), initials);
        expect(book.codeFor(_p(initials)), summonAbilityCode(ability));
      }
    });
  });

  group('armor dictionary vectors', () {
    test('the complete meaningful set under rivendell 4', () {
      final book = _armorBook(_rivendell());
      expect(book.meaningfulPatternCount, _kRivendellArmor.length);
      for (var rank = 0; rank < _kRivendellArmor.length; rank++) {
        final (initials, keyword) = _kRivendellArmor[rank];
        expect(_s(book.orderedPatterns[rank]), initials,
            reason: 'rank $rank of the derived order');
        expect(book.codeFor(_p(initials)), armorKeywordCode(keyword));
        expect(_s(book.patternFor(armorKeywordCode(keyword))!), initials);
      }
    });

    test('the patterns just past the prefix are inert', () {
      final book = _armorBook(_rivendell());
      for (var i = 0; i < _kRivendellArmorInert.length; i++) {
        final initials = _kRivendellArmorInert[i];
        expect(_s(book.orderedPatterns[_kRivendellArmor.length + i]), initials);
        expect(book.codeFor(_p(initials)), isNull);
      }
    });

    test('a different seed is a different dictionary', () {
      final book = _armorBook(_glassmountain());
      for (var rank = 0; rank < _kGlassmountainArmor.length; rank++) {
        final (initials, keyword) = _kGlassmountainArmor[rank];
        expect(_s(book.orderedPatterns[rank]), initials);
        expect(book.codeFor(_p(initials)), armorKeywordCode(keyword));
      }
    });
  });

  // ── Shape ──────────────────────────────────────────────────────────────────

  group('shape', () {
    test('the key space is the 256 four-element patterns', () {
      expect(kLeylinePatternLength, 4);
      expect(kLeylinePatternSpaceSize, 256);
      final book = _summonBook(_rivendell());
      expect(book.orderedPatterns, hasLength(256));
      expect(book.orderedPatterns.toSet(), hasLength(256),
          reason: 'the permutation must be a bijection over the key space');
      for (final pattern in book.orderedPatterns) {
        expect(pattern, hasLength(4));
      }
    });

    test('meaningful patterns are SPARSE — the ordinary cardinality', () {
      // The review gate's named failure: "half of all sliding 4-element windows
      // suddenly become abilities". Eight and seven, not 128.
      expect(_summonBook(_rivendell()).meaningfulPatternCount, 8);
      expect(_armorBook(_rivendell()).meaningfulPatternCount, 7);
      expect(SummonAbility.values, hasLength(8));
      expect(ArmorKeyword.values, hasLength(7));
    });

    test('every output owns exactly one pattern', () {
      // R-8's cardinality-preservation rule: ordinary has one pattern per
      // output, so mutable does too.
      for (final book in [_summonBook(_rivendell()), _armorBook(_rivendell())]) {
        final codes = <int>{};
        for (final pattern in book.orderedPatterns) {
          final code = book.codeFor(pattern);
          if (code != null) {
            expect(codes.add(code), isTrue,
                reason: 'code $code was dealt twice');
          }
        }
        expect(codes, hasLength(book.meaningfulPatternCount));
      }
    });

    test('the ordinary tables also have exactly one pattern per output', () {
      // The premise the rule above preserves, asserted rather than assumed.
      expect(kSummonAbilityPattern, hasLength(SummonAbility.values.length));
      expect(kSummonAbilityPattern.values.toSet(),
          hasLength(SummonAbility.values.length));
      expect(armorKeywordPatterns, hasLength(ArmorKeyword.values.length));
      expect(
        armorKeywordPatterns.values.map((p) => p.map(summonInitial).join()).toSet(),
        hasLength(ArmorKeyword.values.length),
      );
      for (final p in kSummonAbilityPattern.values) {
        expect(p.length, kLeylinePatternLength);
      }
      for (final p in armorKeywordPatterns.values) {
        expect(p.length, kLeylinePatternLength);
      }
    });

    test('canonical enumeration is base-4, most significant element first', () {
      expect(leylineCanonicalPatternAt(0), _p('FFFF'));
      expect(leylineCanonicalPatternAt(1), _p('FFFA'));
      expect(leylineCanonicalPatternAt(4), _p('FFAF'));
      expect(leylineCanonicalPatternAt(255), _p('EEEE'));
      for (var i = 0; i < kLeylinePatternSpaceSize; i++) {
        expect(leylineCanonicalPatternIndex(leylineCanonicalPatternAt(i)), i);
      }
    });
  });

  // ── The projections that make this a ruling and not an accident ────────────

  group('the config-field projection (R-8)', () {
    test('formula length does not rekey either dictionary', () {
      // The review gate's named failure: "formulaLength 5 turns Armor matching
      // into 5-element windows" — and its quieter sibling, formulaLength 5
      // silently rerolling which windows mean anything.
      for (final length in [4, 5, 6]) {
        final config = _rivendell(length: length);
        expect(_summonBook(config).orderedPatterns,
            _summonBook(_rivendell()).orderedPatterns);
        expect(_armorBook(config).orderedPatterns,
            _armorBook(_rivendell()).orderedPatterns);
      }
    });

    test('noise density does not rekey either dictionary', () {
      for (final noise in [0, 333, 500, 999]) {
        final config = _rivendell(noise: noise);
        expect(_summonBook(config).orderedPatterns,
            _summonBook(_rivendell()).orderedPatterns);
        expect(_armorBook(config).orderedPatterns,
            _armorBook(_rivendell()).orderedPatterns);
      }
    });

    test('but the INCANTATION codebook still moves with both', () {
      // The other half of the projection: these fields are that domain's own
      // controls, and they must keep working there.
      final base = IncantationCodebook.derive(_rivendell());
      expect(IncantationCodebook.derive(_rivendell(length: 5)).keyLength,
          isNot(base.keyLength));
      expect(IncantationCodebook.derive(_rivendell(noise: 333)).orderedKeys,
          isNot(base.orderedKeys));
    });
  });

  group('domain separation (§9)', () {
    test('one tradition, three unrelated orderings', () {
      final config = _rivendell();
      final summon = _summonBook(config).orderedPatterns;
      final armor = _armorBook(config).orderedPatterns;
      expect(summon, isNot(armor),
          reason: 'the summon and armor tags must not produce one ordering');
      // And against Incantation: at L=5 its keys are also four elements long,
      // which is exactly the case where a shared tag would be invisible.
      final incantation = IncantationCodebook.derive(_rivendell(length: 5))
          .orderedKeys;
      expect(incantation.first.length, 4, reason: 'fixture sanity');
      expect(summon, isNot(incantation));
      expect(armor, isNot(incantation));
    });

    test('knowing the summon dictionary reveals no armor pattern', () {
      // Six names appear in both vocabularies. None of them shares a pattern —
      // which is what "independently derived" has to mean in practice.
      final summon = _summonBook(_rivendell());
      final armor = _armorBook(_rivendell());
      for (final keyword in ArmorKeyword.values) {
        final ability = SummonAbility.values
            .where((a) => a.name == keyword.name)
            .firstOrNull;
        if (ability == null) continue;
        expect(
          _s(armor.patternFor(armorKeywordCode(keyword))!),
          isNot(_s(summon.patternFor(summonAbilityCode(ability))!)),
          reason: '${keyword.name} shares a pattern across two domains',
        );
      }
    });

    test('the domain tags are the plan\'s literal strings', () {
      expect(kLeylineSummonDomain, 'Runewright/Leyline/v1/Summon');
      expect(kLeylineArmorDomain, 'Runewright/Leyline/v1/Armor');
      expect(kLeylineIncantationDomain, 'Runewright/Leyline/v1/Incantation');
    });
  });

  // ── Guard rails ────────────────────────────────────────────────────────────

  group('guard rails', () {
    test('an ordinary leyline has no derived dictionary', () {
      for (final config in [
        LeylineConfig.ordinaryDefault,
        LeylineConfig.ordinary('rivendell'),
      ]) {
        expect(() => _summonBook(config), throwsA(isA<LeylineConfigException>()));
        expect(() => _armorBook(config), throwsA(isA<LeylineConfigException>()));
      }
    });

    test('derivation is deterministic across repeated calls', () {
      final a = _summonBook(_rivendell());
      final b = _summonBook(_rivendell());
      expect(a.orderedPatterns, b.orderedPatterns);
      expect(a.outputOrder, b.outputOrder);
    });

    test('the output order does not depend on the order codes are fed in', () {
      // The sort's tiebreak is total over the pinned codes, so `List.sort`'s
      // instability cannot reach the result.
      final forward = LeylinePatternCodebook.derive(
        config: _rivendell(),
        domainTag: kLeylineSummonDomain,
        outputCodes: [for (final a in SummonAbility.values) summonAbilityCode(a)],
      );
      final reversed = LeylinePatternCodebook.derive(
        config: _rivendell(),
        domainTag: kLeylineSummonDomain,
        outputCodes: [
          for (final a in SummonAbility.values.reversed) summonAbilityCode(a),
        ],
      );
      expect(reversed.outputOrder, forward.outputOrder);
      for (final pattern in forward.orderedPatterns) {
        expect(reversed.codeFor(pattern), forward.codeFor(pattern));
      }
    });

    test('canonical codes are pinned, not enum indices', () {
      // Today they coincide, which is why the coincidence is asserted: the
      // moment someone reorders either enum the two diverge, and a `.index`
      // here would silently reroll every mutable leyline's dictionary.
      for (final a in SummonAbility.values) {
        expect(summonAbilityCode(a), a.index,
            reason: 'if you reordered SummonAbility, update '
                'kSummonAbilityCode to KEEP the old codes — do not update this '
                'expectation');
      }
      for (final k in ArmorKeyword.values) {
        expect(armorKeywordCode(k), k.index,
            reason: 'if you reordered ArmorKeyword, update kArmorKeywordCode '
                'to KEEP the old codes — do not update this expectation');
      }
      expect(kSummonAbilityCode.values.toSet(), hasLength(8));
      expect(kArmorKeywordCode.values.toSet(), hasLength(7));
    });

    test('a malformed vocabulary is refused', () {
      expect(
        () => LeylinePatternCodebook.derive(
          config: _rivendell(),
          domainTag: kLeylineSummonDomain,
          outputCodes: const [],
        ),
        throwsArgumentError,
      );
      expect(
        () => LeylinePatternCodebook.derive(
          config: _rivendell(),
          domainTag: kLeylineSummonDomain,
          outputCodes: const [1, 1],
        ),
        throwsArgumentError,
      );
    });

    test('a wrong-length pattern is an error, not an inert lookup', () {
      // Conflating "this leyline says nothing" with "you asked the wrong
      // question" is how a windowing bug becomes a silently ability-less
      // creature instead of a crash.
      final book = _summonBook(_rivendell());
      expect(() => book.codeFor(_p('FFF')), throwsArgumentError);
      expect(() => book.codeFor(_p('FFFFF')), throwsArgumentError);
    });
  });
}
