// SPDX-License-Identifier: GPL-3.0-or-later
//
// leyline_codebook_test.dart — the load-bearing vectors for Mutable Leyline
// incantation-codebook derivation (docs/LEYLINE_SEED_PLAN.md §4, §5, §15;
// audit Slice B).
//
// ## These are a CROSS-CLIENT CONTRACT
//
// §15: *"Every peer must derive byte-identical codebooks from the same
// configuration."* Two devices that disagree about what `earth-water-fire` means
// under `rivendell 4` resolve different spells from the same certified
// trajectory. So a refactor that changes any pinned literal below is a BREAKING
// CONSENSUS CHANGE requiring a `lexiconVersion` bump, not a test that needs
// updating. If one fails, the change is wrong until proven otherwise.
//
// ## Where the constants came from
//
// **Not from running the code under test.** Every literal here is the output of
// `scripts/gen_leyline_codebook_vectors.py`, a from-scratch second
// implementation written against the byte layout documented in
// `leyline_codebook.dart`'s header rather than transcribed from it. A vector
// generated by the implementation it guards only proves determinism; it cannot
// catch a transcription error, because the error would be in both halves. That
// script also recomputes `leylineConfigHash` independently and reproduces
// `leyline_config_test.dart`'s pinned hashes exactly, which is why the config
// hashes appear here too — they are the derivation's anchor, and a second
// attestation of them is free.
//
// ## Slice B posture
//
// Nothing in production reads a codebook yet. These vectors exist so that the
// day something does (audit Slice D), the bytes are already the ones two
// independent implementations agreed on.

import 'package:test/test.dart';

import 'package:rune_duel/battle/models/effect_kind.dart';
import 'package:rune_duel/battle/models/leyline_codebook.dart';
import 'package:rune_duel/battle/models/leyline_config.dart';
import 'package:rune_duel/engine/border_zone.dart';

/// The per-effect key counts of [book], in `EffectKind` declaration order —
/// the shape `gen_leyline_codebook_vectors.py` prints.
List<int> _countsInDeclarationOrder(IncantationCodebook book) {
  final counts = book.perEffectKeyCounts;
  return [for (final kind in EffectKind.values) counts[kind]!];
}

/// The derived-order noise keys of [book].
List<List<BorderZone>> _noiseKeys(IncantationCodebook book) => [
      for (final key in book.orderedKeys)
        if (book.lookup(key) is IncantationNoise) key,
    ];

/// The meanings of [book]'s first [n] ordered keys.
List<EffectKind> _firstMeanings(IncantationCodebook book, int n) => [
      for (final key in book.orderedKeys.take(n))
        (book.lookup(key) as IncantationEffect).kind,
    ];

void main() {
  // ── §5's ratified count table ────────────────────────────────────────────

  group('§5 count table (RATIFIED)', () {
    test('50% at each supported length yields the plan\'s exact counts', () {
      // The table §5 pins: 64/32, 256/128, 1024/512 — 2, 8 and 32 keys per
      // effect. Round-half-up on the noise count reproduces it exactly, which
      // is the reason that rounding was chosen over floor or ceil.
      for (final (length, total, meaningful) in [
        (4, 64, 32),
        (5, 256, 128),
        (6, 1024, 512),
      ]) {
        final book = IncantationCodebook.derive(
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: length),
        );
        expect(book.totalKeyCount, total, reason: 'L=$length total');
        expect(book.meaningfulKeyCount, meaningful, reason: 'L=$length meaningful');
        expect(book.noiseKeyCount, total - meaningful, reason: 'L=$length noise');
        expect(
          _countsInDeclarationOrder(book),
          everyElement(meaningful ~/ 16),
          reason: 'L=$length must be exactly even — §5 "every effect remains '
              'equally available"',
        );
      }
    });
  });

  // ── The fixed vectors ────────────────────────────────────────────────────

  group('codebook vectors (CROSS-CLIENT CONTRACT)', () {
    test("mutable('rivendell', length 4, 500‰)", () {
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4);
      expect(
        config.leylineConfigHash,
        '2b3f90cb9a5bc08b7c7e48457cae8c92c87c1b3616c11dd617b9f76df783a815',
      );
      final book = IncantationCodebook.derive(config);

      expect(book.keyLength, 3);
      expect(book.totalKeyCount, 64);
      expect(book.meaningfulKeyCount, 32);
      expect(book.noiseKeyCount, 32);

      expect(book.effectOrder, const [
        EffectKind.tileModification,
        EffectKind.clouds,
        EffectKind.haymakerInteraction,
        EffectKind.multiplierCycles,
        EffectKind.illusions,
        EffectKind.divination,
        EffectKind.spellInteraction,
        EffectKind.speedManipulation,
        EffectKind.artifactsInteraction,
        EffectKind.rangeModification,
        EffectKind.chainInteraction,
        EffectKind.statusEffectInteraction,
        EffectKind.reflections,
        EffectKind.barrier,
        EffectKind.damage,
        EffectKind.fuelTransmutation,
      ]);

      expect(book.orderedKeys.take(4), const [
        [BorderZone.earth, BorderZone.water, BorderZone.fire],
        [BorderZone.air, BorderZone.air, BorderZone.earth],
        [BorderZone.fire, BorderZone.water, BorderZone.fire],
        [BorderZone.fire, BorderZone.air, BorderZone.earth],
      ]);
      expect(_firstMeanings(book, 4), const [
        EffectKind.tileModification,
        EffectKind.clouds,
        EffectKind.haymakerInteraction,
        EffectKind.multiplierCycles,
      ]);

      expect(_noiseKeys(book).take(4), const [
        [BorderZone.water, BorderZone.fire, BorderZone.fire],
        [BorderZone.air, BorderZone.earth, BorderZone.earth],
        [BorderZone.earth, BorderZone.fire, BorderZone.fire],
        [BorderZone.fire, BorderZone.earth, BorderZone.air],
      ]);

      expect(_countsInDeclarationOrder(book),
          const [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]);
    });

    test("mutable('rivendell', length 5, 500‰)", () {
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 5);
      expect(
        config.leylineConfigHash,
        'e7bad03c277f8a1c08cb0ef2e4ab355270ba371c42faa8d63d02fadf1879cbff',
      );
      final book = IncantationCodebook.derive(config);

      expect(book.keyLength, 4);
      expect(book.totalKeyCount, 256);
      expect(book.meaningfulKeyCount, 128);
      expect(book.noiseKeyCount, 128);

      expect(book.effectOrder.take(4), const [
        EffectKind.clouds,
        EffectKind.multiplierCycles,
        EffectKind.divination,
        EffectKind.reflections,
      ]);

      expect(book.orderedKeys.take(4), const [
        [BorderZone.earth, BorderZone.air, BorderZone.water, BorderZone.air],
        [BorderZone.air, BorderZone.earth, BorderZone.water, BorderZone.fire],
        [BorderZone.air, BorderZone.fire, BorderZone.water, BorderZone.air],
        [BorderZone.earth, BorderZone.water, BorderZone.water, BorderZone.water],
      ]);
      expect(_firstMeanings(book, 4), const [
        EffectKind.clouds,
        EffectKind.multiplierCycles,
        EffectKind.divination,
        EffectKind.reflections,
      ]);

      expect(_noiseKeys(book).take(4), const [
        [BorderZone.water, BorderZone.fire, BorderZone.earth, BorderZone.water],
        [BorderZone.earth, BorderZone.air, BorderZone.water, BorderZone.water],
        [BorderZone.water, BorderZone.water, BorderZone.water, BorderZone.fire],
        [BorderZone.fire, BorderZone.water, BorderZone.fire, BorderZone.water],
      ]);

      expect(_countsInDeclarationOrder(book),
          const [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]);
    });

    test("mutable('rivendell', length 6, 500‰)", () {
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 6);
      expect(
        config.leylineConfigHash,
        'd2f85313ac7906a21d216c4a1b01b7cc1bfa54aca69787945158b631e902b18d',
      );
      final book = IncantationCodebook.derive(config);

      expect(book.keyLength, 5);
      expect(book.totalKeyCount, 1024);
      expect(book.meaningfulKeyCount, 512);
      expect(book.noiseKeyCount, 512);

      expect(book.effectOrder.take(4), const [
        EffectKind.fuelTransmutation,
        EffectKind.statusEffectInteraction,
        EffectKind.reflections,
        EffectKind.spellInteraction,
      ]);

      expect(book.orderedKeys.take(4), const [
        [BorderZone.fire, BorderZone.water, BorderZone.earth, BorderZone.water, BorderZone.air],
        [BorderZone.water, BorderZone.fire, BorderZone.air, BorderZone.water, BorderZone.earth],
        [BorderZone.fire, BorderZone.air, BorderZone.earth, BorderZone.fire, BorderZone.fire],
        [BorderZone.fire, BorderZone.earth, BorderZone.water, BorderZone.air, BorderZone.water],
      ]);
      expect(_firstMeanings(book, 4), const [
        EffectKind.fuelTransmutation,
        EffectKind.statusEffectInteraction,
        EffectKind.reflections,
        EffectKind.spellInteraction,
      ]);

      expect(_noiseKeys(book).take(4), const [
        [BorderZone.earth, BorderZone.earth, BorderZone.air, BorderZone.earth, BorderZone.air],
        [BorderZone.water, BorderZone.air, BorderZone.earth, BorderZone.air, BorderZone.earth],
        [BorderZone.earth, BorderZone.air, BorderZone.water, BorderZone.water, BorderZone.water],
        [BorderZone.air, BorderZone.fire, BorderZone.fire, BorderZone.fire, BorderZone.water],
      ]);

      expect(_countsInDeclarationOrder(book), everyElement(32));
    });

    test("mutable('glassmountain', length 4, 500‰) — a second tradition", () {
      // The same length and density under a different seed must be a wholly
      // different dictionary, not a relabelling of the first.
      final config = LeylineConfig.mutable(
        communitySeed: 'glassmountain',
        formulaLength: 4,
      );
      expect(
        config.leylineConfigHash,
        '8e4a49ee49ce0983aedea984a62f7041aa5dcad9dbe07900e7a0349f373efced',
      );
      final book = IncantationCodebook.derive(config);

      expect(book.orderedKeys.take(4), const [
        [BorderZone.fire, BorderZone.fire, BorderZone.water],
        [BorderZone.water, BorderZone.earth, BorderZone.earth],
        [BorderZone.earth, BorderZone.water, BorderZone.earth],
        [BorderZone.water, BorderZone.fire, BorderZone.earth],
      ]);
      expect(_firstMeanings(book, 4), const [
        EffectKind.fuelTransmutation,
        EffectKind.multiplierCycles,
        EffectKind.chainInteraction,
        EffectKind.speedManipulation,
      ]);
      expect(_countsInDeclarationOrder(book), everyElement(2));

      final rivendell = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      expect(book.orderedKeys, isNot(rivendell.orderedKeys));
      expect(book.effectOrder, isNot(rivendell.effectOrder));
    });
  });

  // ── 0‰: a pure permutation ───────────────────────────────────────────────

  group('0‰ — a permutation with no noise', () {
    test("mutable('rivendell', length 4, 0‰)", () {
      final config = LeylineConfig.mutable(
        communitySeed: 'rivendell',
        formulaLength: 4,
        noiseDensityPermille: 0,
      );
      expect(
        config.leylineConfigHash,
        'e788786f32e1a8a99452ff2f5d10d5317bc42ef44fc93ded37d02e241d8e6141',
      );
      final book = IncantationCodebook.derive(config);

      expect(book.noiseKeyCount, 0);
      expect(book.meaningfulKeyCount, 64);
      expect(_noiseKeys(book), isEmpty);
      expect(_countsInDeclarationOrder(book), everyElement(4));

      expect(book.orderedKeys.take(4), const [
        [BorderZone.earth, BorderZone.water, BorderZone.air],
        [BorderZone.air, BorderZone.fire, BorderZone.water],
        [BorderZone.water, BorderZone.air, BorderZone.fire],
        [BorderZone.air, BorderZone.air, BorderZone.water],
      ]);
      expect(_firstMeanings(book, 4), const [
        EffectKind.fuelTransmutation,
        EffectKind.chainInteraction,
        EffectKind.reflections,
        EffectKind.tileModification,
      ]);

      // Density is part of the config hash, so 0‰ is not "500‰ with the noise
      // removed" — it is a different leyline with a different permutation.
      final at500 = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      expect(book.orderedKeys, isNot(at500.orderedKeys));
    });
  });

  // ── The non-divisible case (audit §5.2 item 3) ───────────────────────────

  group('333‰ at L=4 — rounding and the remainder', () {
    late IncantationCodebook book;

    setUp(() {
      final config = LeylineConfig.mutable(
        communitySeed: 'rivendell',
        formulaLength: 4,
        noiseDensityPermille: 333,
      );
      expect(
        config.leylineConfigHash,
        'b0cf92458e77680a9a5dfbf353336d6aaa9fbdcbd84acd9e3338fe5431ddc488',
      );
      book = IncantationCodebook.derive(config);
    });

    test('round-half-up gives 21 noise / 43 meaningful', () {
      // (64 * 333 + 500) ~/ 1000 = 21. The audit's own worked example.
      expect(book.noiseKeyCount, 21);
      expect(book.meaningfulKeyCount, 43);
    });

    test('per-effect counts differ by exactly one', () {
      expect(_countsInDeclarationOrder(book),
          const [3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 3, 3, 2]);
      final counts = _countsInDeclarationOrder(book);
      expect(counts.reduce((a, b) => a + b), 43);
      expect(counts.reduce((a, b) => a > b ? a : b) -
          counts.reduce((a, b) => a < b ? a : b),
          1);
    });

    test('the extra key goes to a PREFIX OF THE DERIVED effect order, '
        'not to low effect codes', () {
      // R-4, stated as an assertion: 43 % 16 = 11, so exactly the first
      // eleven effects of THIS leyline's derived order own three keys. Under a
      // fixed effect order those eleven would be the same eleven under every
      // leyline at every non-divisible density — a permanent, discoverable,
      // leyline-independent bias. Here they are not.
      final counts = book.perEffectKeyCounts;
      final extra = book.effectOrder.take(43 % 16).toSet();
      expect(extra.length, 11);
      for (final kind in EffectKind.values) {
        expect(counts[kind], extra.contains(kind) ? 3 : 2,
            reason: '${kind.name} should have ${extra.contains(kind) ? 3 : 2}');
      }
      // And the eleven are NOT simply effect codes 0..10.
      expect(
        extra.map(incantationEffectCode).toList()..sort(),
        isNot(List.generate(11, (i) => i)),
      );
    });

    test('the first ordered keys and noise keys are pinned', () {
      expect(book.orderedKeys.take(4), const [
        [BorderZone.air, BorderZone.water, BorderZone.earth],
        [BorderZone.water, BorderZone.earth, BorderZone.air],
        [BorderZone.fire, BorderZone.water, BorderZone.earth],
        [BorderZone.fire, BorderZone.fire, BorderZone.water],
      ]);
      expect(_noiseKeys(book).take(4), const [
        [BorderZone.earth, BorderZone.earth, BorderZone.fire],
        [BorderZone.air, BorderZone.air, BorderZone.air],
        [BorderZone.fire, BorderZone.earth, BorderZone.earth],
        [BorderZone.fire, BorderZone.fire, BorderZone.air],
      ]);
    });
  });

  // ── The noise-count arithmetic in isolation (R-2) ────────────────────────

  group('leylineNoiseKeyCount (R-2)', () {
    test('pinned edge cases', () {
      // Round-half-up, integer arithmetic. Each pinned independently by the
      // Python generator.
      expect(leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 0), 0);
      expect(leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 1), 0);
      expect(leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 7), 0);
      // 64 * 8 / 1000 = 0.512 — the first density that rounds UP to one key.
      expect(leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 8), 1);
      expect(leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 500), 32);
      expect(leylineNoiseKeyCount(totalKeyCount: 256, noiseDensityPermille: 333), 85);
      expect(leylineNoiseKeyCount(totalKeyCount: 1024, noiseDensityPermille: 333), 341);
      expect(leylineNoiseKeyCount(totalKeyCount: 1024, noiseDensityPermille: 999), 1023);
    });

    test('999‰ at L=4 rounds to an ALL-NOISE codebook — reachable, unclamped', () {
      // (64 * 999 + 500) ~/ 1000 = 64. LeylineConfig rejects 1000‰ because a
      // leyline in which nothing means anything is not magic; rounding reaches
      // the same place from 999‰ at the smallest key space. Pinned rather than
      // clamped because a floor would be a NEW consensus rule that no plan
      // states — see this slice's report. If a floor is later ruled, this test
      // is the one that changes.
      expect(leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 999), 64);
      final book = IncantationCodebook.derive(LeylineConfig.mutable(
        communitySeed: 'rivendell',
        formulaLength: 4,
        noiseDensityPermille: 999,
      ));
      expect(book.meaningfulKeyCount, 0);
      expect(_countsInDeclarationOrder(book), everyElement(0));
      // Degenerate, but structurally sound: still a total mapping, still 64
      // keys, no crash and no silent partial dictionary.
      expect(book.orderedKeys, hasLength(64));
      expect(_noiseKeys(book), hasLength(64));
    });

    test('a meaningful count below 16 still spreads one key per effect', () {
      // Round-robin's degradation, which blocked allocation could not express:
      // 1024 keys at 999‰ leaves exactly one meaningful key, and it belongs to
      // the first effect of the derived order — not to effect code 0.
      final book = IncantationCodebook.derive(LeylineConfig.mutable(
        communitySeed: 'rivendell',
        formulaLength: 6,
        noiseDensityPermille: 999,
      ));
      expect(book.meaningfulKeyCount, 1);
      final counts = book.perEffectKeyCounts;
      expect(counts[book.effectOrder.first], 1);
      expect(counts.values.where((c) => c == 1), hasLength(1));
    });

    test('rejects an out-of-range density', () {
      expect(
        () => leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: 1001),
        throwsArgumentError,
      );
      expect(
        () => leylineNoiseKeyCount(totalKeyCount: 64, noiseDensityPermille: -1),
        throwsArgumentError,
      );
    });
  });

  // ── Order independence (R-1's whole point) ───────────────────────────────

  group('order independence and determinism', () {
    test('deriving twice gives an identical codebook', () {
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 5);
      final a = IncantationCodebook.derive(config);
      final b = IncantationCodebook.derive(config);
      expect(a.orderedKeys, b.orderedKeys);
      expect(a.effectOrder, b.effectOrder);
      for (final key in a.orderedKeys) {
        expect(a.lookup(key), b.lookup(key));
      }
    });

    test('every key\'s rank is independently computable from its own score', () {
      // THE order-independence evidence. Sort-by-hash was chosen (R-1,
      // candidate B) precisely so that an entry's position depends on nothing
      // but its own score and the scores it is compared against — never on
      // arrival order, insertion order, or a shuffle's internal state. That
      // property is checkable directly: recompute each key's rank as "how many
      // keys sort before me", from scratch, and it must equal the position the
      // derivation put it in.
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4);
      final book = IncantationCodebook.derive(config);

      List<int> payloadOf(List<BorderZone> key) =>
          [for (final e in key) leylineKeyElementCode(e)];
      int compare(List<int> a, List<int> b) {
        for (var i = 0; i < a.length && i < b.length; i++) {
          if (a[i] != b[i]) return a[i] < b[i] ? -1 : 1;
        }
        return a.length.compareTo(b.length);
      }

      final all = [
        for (var i = 0; i < book.totalKeyCount; i++) book.canonicalKeyAt(i),
      ];
      // Positions keyed by canonical index, not by `indexOf`: Dart's `==` on
      // `List` is identity, so `orderedKeys.indexOf(aFreshlyBuiltKey)` is
      // always -1. The canonical index is the key's identity here.
      final position = <int, int>{
        for (var i = 0; i < book.orderedKeys.length; i++)
          book.canonicalKeyIndex(book.orderedKeys[i]): i,
      };
      for (final key in all) {
        final score = leylineStreamScore(
          domainTag: kLeylineIncantationDomain,
          config: config,
          streamTag: kLeylineKeyOrderStream,
          payload: payloadOf(key),
        );
        var rank = 0;
        for (final other in all) {
          if (identical(other, key)) continue;
          final otherScore = leylineStreamScore(
            domainTag: kLeylineIncantationDomain,
            config: config,
            streamTag: kLeylineKeyOrderStream,
            payload: payloadOf(other),
          );
          final byScore = compare(otherScore, score);
          if (byScore < 0 ||
              (byScore == 0 && compare(payloadOf(other), payloadOf(key)) < 0)) {
            rank++;
          }
        }
        expect(position[book.canonicalKeyIndex(key)], rank,
            reason: 'rank of $key must be computable without the sort');
      }
    });

    test('the derived order is a permutation of the canonical enumeration', () {
      // Not a sample, not a filter: every key appears exactly once. A sort that
      // dropped or duplicated an entry would silently give some tail no meaning
      // at all, which is a different failure from "noise".
      for (final length in [4, 5]) {
        final book = IncantationCodebook.derive(
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: length),
        );
        final seen = book.orderedKeys.map(book.canonicalKeyIndex).toSet();
        expect(seen, hasLength(book.totalKeyCount));
        expect(seen.reduce((a, b) => a > b ? a : b), book.totalKeyCount - 1);
        expect(seen.reduce((a, b) => a < b ? a : b), 0);
      }
    });

    test('an equal config built by a different route derives the same book', () {
      // The construction reads only the config's canonical fields, so two
      // configs that are `==` must be indistinguishable to it.
      final a = LeylineConfig.mutable(
        communitySeed: 'rivendell',
        formulaLength: 4,
        noiseDensityPermille: 500,
      );
      final b = LeylineConfig.fromJson(const {
        'communitySeed': 'Rivendell!',
        'mutableMagic': true,
        'formulaLength': 4,
        'noiseDensityPermille': 500,
        'lexiconVersion': 1,
      });
      expect(a, b);
      expect(IncantationCodebook.derive(a).orderedKeys,
          IncantationCodebook.derive(b).orderedKeys);
    });
  });

  // ── Normalization ────────────────────────────────────────────────────────

  group('seed normalization', () {
    test('equivalent spellings derive one codebook', () {
      final canonical = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      for (final spelling in [
        'Rivendell',
        'RIVENDELL',
        '  rivendell  ',
        'Rivendell!',
        'ri-ven-dell',
        'R I V E N D E L L',
      ]) {
        final book = IncantationCodebook.derive(
          LeylineConfig.mutable(communitySeed: spelling, formulaLength: 4),
        );
        expect(book.orderedKeys, canonical.orderedKeys,
            reason: '"$spelling" must be the same tradition');
        expect(book.effectOrder, canonical.effectOrder, reason: '"$spelling"');
        for (final key in canonical.orderedKeys) {
          expect(book.lookup(key), canonical.lookup(key), reason: '"$spelling"');
        }
      }
    });

    test('a seed that normalizes to nothing falls back to the default', () {
      expect(
        IncantationCodebook.derive(
          LeylineConfig.mutable(communitySeed: '---', formulaLength: 4),
        ).orderedKeys,
        IncantationCodebook.derive(
          LeylineConfig.mutable(
            communitySeed: kDefaultCommunitySeed,
            formulaLength: 4,
          ),
        ).orderedKeys,
      );
    });
  });

  // ── Domain separation ────────────────────────────────────────────────────

  group('domain separation', () {
    test('the three pinned tags are the plan\'s literal strings', () {
      // §4, §8, §9, transcribed. Pinned because a tag typo is undetectable at
      // runtime — it just produces a different, self-consistent dictionary.
      expect(kLeylineIncantationDomain, 'Runewright/Leyline/v1/Incantation');
      expect(kLeylineSummonDomain, 'Runewright/Leyline/v1/Summon');
      expect(kLeylineArmorDomain, 'Runewright/Leyline/v1/Armor');
    });

    test('identical inputs under a different tag order differently', () {
      // §8: *"Knowledge of the incantation dictionary must reveal nothing about
      // the summon dictionary."* Summon and Armor key spaces are NOT defined
      // yet (audit R-8); this exercises the primitive over the incantation key
      // space under all three tags purely to prove the separation is real.
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4);
      const key = [BorderZone.earth, BorderZone.water, BorderZone.fire];
      final payload = [for (final e in key) leylineKeyElementCode(e)];

      final scores = {
        for (final tag in [
          kLeylineIncantationDomain,
          kLeylineSummonDomain,
          kLeylineArmorDomain,
        ])
          tag: leylineStreamScore(
            domainTag: tag,
            config: config,
            streamTag: kLeylineKeyOrderStream,
            payload: payload,
          ).join(','),
      };
      expect(scores.values.toSet(), hasLength(3),
          reason: 'three tags, three scores');
    });

    test('the two streams of one tag are separated too', () {
      // A one-byte effect-code payload and a one-byte key payload must not be
      // able to share a preimage. They cannot today (the shortest legal key is
      // three elements), but the stream tag is what makes that a property of
      // the encoding rather than of a length bound that may later move.
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4);
      final asKey = leylineStreamScore(
        domainTag: kLeylineIncantationDomain,
        config: config,
        streamTag: kLeylineKeyOrderStream,
        payload: const [1],
      );
      final asEffect = leylineStreamScore(
        domainTag: kLeylineIncantationDomain,
        config: config,
        streamTag: kLeylineEffectOrderStream,
        payload: const [1],
      );
      expect(asKey, isNot(asEffect));
    });
  });

  // ── The key space (canonical encoding) ───────────────────────────────────

  group('canonical key encoding', () {
    test('the alphabet is the four elements in circuit order, no neutral', () {
      // circuits/GRID_ORDERING_v2.md §Rule indices: 1 Fire, 2 Air, 3 Water,
      // 4 Earth. Neutral's 0 is never a formula element — FormulaTracker
      // commits nothing on a neutral or tied generation — so the tail space is
      // 4^(L-1) exactly as §3 says, not 5^(L-1).
      expect(kLeylineKeyAlphabet, const [
        BorderZone.fire,
        BorderZone.air,
        BorderZone.water,
        BorderZone.earth,
      ]);
      expect(kLeylineKeyAlphabet.map(leylineKeyElementCode), const [1, 2, 3, 4]);
    });

    test('enumeration is lexicographic, most significant element first', () {
      final book = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      expect(book.canonicalKeyAt(0),
          const [BorderZone.fire, BorderZone.fire, BorderZone.fire]);
      expect(book.canonicalKeyAt(1),
          const [BorderZone.fire, BorderZone.fire, BorderZone.air]);
      expect(book.canonicalKeyAt(4),
          const [BorderZone.fire, BorderZone.air, BorderZone.fire]);
      expect(book.canonicalKeyAt(16),
          const [BorderZone.air, BorderZone.fire, BorderZone.fire]);
      expect(book.canonicalKeyAt(63),
          const [BorderZone.earth, BorderZone.earth, BorderZone.earth]);
    });

    test('canonicalKeyIndex and canonicalKeyAt are inverse', () {
      final book = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 5),
      );
      for (var i = 0; i < book.totalKeyCount; i++) {
        expect(book.canonicalKeyIndex(book.canonicalKeyAt(i)), i);
      }
    });

    test('effect ORDER is keyed on the pinned code, not on enum order', () {
      // RATIFIED: both places an effect's identity is consulted during
      // derivation use kIncantationEffectCode — the scoring payload and the
      // sort's tiebreak. `EffectKind.values` is only the enumeration source,
      // and the tiebreak is total over sixteen distinct codes, so the input
      // order cannot reach the result. Recompute the whole order from a
      // REVERSED input using only the pinned codes; it must match.
      final config =
          LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4);

      int compare(List<int> a, List<int> b) {
        for (var i = 0; i < a.length && i < b.length; i++) {
          if (a[i] != b[i]) return a[i] < b[i] ? -1 : 1;
        }
        return a.length.compareTo(b.length);
      }

      final reversed = EffectKind.values.reversed.toList();
      final rebuilt = [
        for (final kind in reversed)
          (
            leylineStreamScore(
              domainTag: kLeylineIncantationDomain,
              config: config,
              streamTag: kLeylineEffectOrderStream,
              payload: [incantationEffectCode(kind)],
            ),
            incantationEffectCode(kind),
            kind,
          ),
      ]..sort((a, b) {
          final byScore = compare(a.$1, b.$1);
          return byScore != 0 ? byScore : a.$2.compareTo(b.$2);
        });

      expect([for (final e in rebuilt) e.$3],
          deriveEffectOrder(config),
          reason: 'the effect order must not depend on EffectKind.values order');
    });

    test('the pinned codes equal declaration order TODAY — a coincidence', () {
      // This test exists to fail loudly the day someone reorders `EffectKind`.
      //
      // Right now `incantationEffectCode(kind) == kind.index` for all sixteen,
      // which means a regression that swapped the pinned map for `.index`
      // would change no byte and move no vector — the hazard is real and
      // currently invisible. Reordering the enum is a legitimate cosmetic edit
      // that makes the two diverge; when it happens, this assertion breaks
      // first and sends the reader to `deriveEffectOrder`'s header, where the
      // rule is written: the pinned code is the identity, `.index` is never.
      //
      // Fixing a failure here means updating THIS test, never the derivation
      // and never `kIncantationEffectCode` — the pinned codes are frozen, and
      // the codebook vectors must not move.
      for (final kind in EffectKind.values) {
        expect(incantationEffectCode(kind), kind.index,
            reason: 'if this fails, EffectKind was reordered: leave '
                'kIncantationEffectCode alone, leave the vectors alone, and '
                'delete this assertion');
      }
    });

    test('effect codes are pinned and total', () {
      expect(kIncantationEffectCode, hasLength(16));
      expect(kIncantationEffectCode.values.toSet(),
          List.generate(16, (i) => i).toSet());
      for (final kind in EffectKind.values) {
        expect(incantationEffectCode(kind), isNotNull);
      }
      expect(incantationEffectCode(EffectKind.damage), 0);
      expect(incantationEffectCode(EffectKind.divination), 15);
    });
  });

  // ── The API's guard rails ────────────────────────────────────────────────

  group('guard rails', () {
    test('an ordinary leyline has no derived codebook', () {
      // The one that matters: ordinary play's sixteen tails are the fixed
      // effectKindFromPair table. A caller that forgot to check mutableMagic
      // would otherwise silently rekey every existing spellbook.
      expect(() => IncantationCodebook.derive(LeylineConfig.ordinaryDefault),
          throwsA(isA<LeylineConfigException>()));
      expect(() => IncantationCodebook.derive(LeylineConfig.ordinary('rivendell')),
          throwsA(isA<LeylineConfigException>()));
    });

    test('a wrong-length key is an error, not noise', () {
      final book = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      expect(() => book.lookup(const [BorderZone.fire]), throwsArgumentError);
      expect(
        () => book.lookup(const [
          BorderZone.fire,
          BorderZone.fire,
          BorderZone.fire,
          BorderZone.fire,
        ]),
        throwsArgumentError,
      );
    });

    test('lookup, keysFor and the counts agree', () {
      final book = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      for (final kind in EffectKind.values) {
        final keys = book.keysFor(kind);
        expect(keys, hasLength(book.perEffectKeyCounts[kind]));
        for (final key in keys) {
          expect(book.lookup(key), IncantationEffect(kind));
        }
      }
      expect(
        book.keysFor(EffectKind.damage).length +
            book.keysFor(EffectKind.barrier).length,
        4,
      );
    });

    test('noise is a distinct, exhaustively switchable meaning', () {
      // The representation ruling, exercised: a consumer must be able to
      // distinguish noise from an effect without a null check, and the
      // analyzer must force it to handle both.
      final book = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      var effects = 0;
      var noise = 0;
      for (final key in book.orderedKeys) {
        switch (book.lookup(key)) {
          case IncantationEffect():
            effects++;
          case IncantationNoise():
            noise++;
        }
      }
      expect(effects, 32);
      expect(noise, 32);
      expect(const IncantationNoise(), kIncantationNoise);
      expect(const IncantationEffect(EffectKind.damage),
          const IncantationEffect(EffectKind.damage));
      expect(const IncantationEffect(EffectKind.damage),
          isNot(const IncantationEffect(EffectKind.barrier)));
    });
  });

  // ── Slice B's central claim ──────────────────────────────────────────────

  group('ordinary behaviour is untouched', () {
    test('effectKindFromPair still decides the ordinary table', () {
      // Slice B changes no ordinary semantics. This is the canary: if the
      // fixed table ever starts agreeing with a derived codebook, something
      // has been wired in that should not have been.
      expect(effectKindFromPair(BorderZone.fire, BorderZone.fire),
          EffectKind.damage);
      expect(effectKindFromPair(BorderZone.air, BorderZone.water),
          EffectKind.divination);

      // And the derived codebook is emphatically NOT that table: under
      // `rivendell 4` the tail `fire-fire-fire` is noise, not Blast.
      final book = IncantationCodebook.derive(
        LeylineConfig.mutable(communitySeed: 'rivendell', formulaLength: 4),
      );
      expect(
        book.lookup(const [BorderZone.fire, BorderZone.fire, BorderZone.fire]),
        kIncantationNoise,
      );
    });

    test('the ordinary formula length is still what segmentation uses', () {
      expect(LeylineConfig.ordinaryDefault.formulaLength, 3);
      expect(LeylineConfig.ordinaryDefault.noiseDensityPermille, 0);
    });
  });
}
