// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/prover.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiProverFrbInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 215746290;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'runewright_ffi',
        ioDirectory: 'ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiProverComputeVk({
    required String circuitBytecode,
    required bool lowMemory,
  });

  Future<Uint8List> crateApiProverComputeVkKeccak({
    required String circuitBytecode,
    required bool lowMemory,
  });

  Future<String> crateApiProverExtractBytecode({required String circuitJson});

  Future<void> crateApiProverFrbInitApp();

  Future<int> crateApiProverInitSrs({
    required String circuitBytecode,
    String? srsPath,
  });

  Future<(int, Uint8List)> crateApiProverInitSrsAndComputeVk({
    required String circuitBytecode,
    String? srsPath,
    required bool lowMemory,
  });

  Future<TimedProofResult> crateApiProverProveAndTime({
    required String circuitBytecode,
    required List<int> gridState,
    required String keyHiHex,
    required String keyLoHex,
    required String tHex,
    required String ownerPubkeyHex,
    required String rulesetVersionHex,
    required List<int> vkBytes,
    required bool lowMemory,
  });

  Future<bool> crateApiProverVerifyProof({
    required List<int> vkBytes,
    required List<int> proofBytes,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiProverComputeVk({
    required String circuitBytecode,
    required bool lowMemory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(circuitBytecode, serializer);
          sse_encode_bool(lowMemory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverComputeVkConstMeta,
        argValues: [circuitBytecode, lowMemory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverComputeVkConstMeta => const TaskConstMeta(
    debugName: "compute_vk",
    argNames: ["circuitBytecode", "lowMemory"],
  );

  @override
  Future<Uint8List> crateApiProverComputeVkKeccak({
    required String circuitBytecode,
    required bool lowMemory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(circuitBytecode, serializer);
          sse_encode_bool(lowMemory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverComputeVkKeccakConstMeta,
        argValues: [circuitBytecode, lowMemory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverComputeVkKeccakConstMeta =>
      const TaskConstMeta(
        debugName: "compute_vk_keccak",
        argNames: ["circuitBytecode", "lowMemory"],
      );

  @override
  Future<String> crateApiProverExtractBytecode({required String circuitJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(circuitJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverExtractBytecodeConstMeta,
        argValues: [circuitJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverExtractBytecodeConstMeta =>
      const TaskConstMeta(
        debugName: "extract_bytecode",
        argNames: ["circuitJson"],
      );

  @override
  Future<void> crateApiProverFrbInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProverFrbInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverFrbInitAppConstMeta =>
      const TaskConstMeta(debugName: "frb_init_app", argNames: []);

  @override
  Future<int> crateApiProverInitSrs({
    required String circuitBytecode,
    String? srsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(circuitBytecode, serializer);
          sse_encode_opt_String(srsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverInitSrsConstMeta,
        argValues: [circuitBytecode, srsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverInitSrsConstMeta => const TaskConstMeta(
    debugName: "init_srs",
    argNames: ["circuitBytecode", "srsPath"],
  );

  @override
  Future<(int, Uint8List)> crateApiProverInitSrsAndComputeVk({
    required String circuitBytecode,
    String? srsPath,
    required bool lowMemory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(circuitBytecode, serializer);
          sse_encode_opt_String(srsPath, serializer);
          sse_encode_bool(lowMemory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_u_32_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverInitSrsAndComputeVkConstMeta,
        argValues: [circuitBytecode, srsPath, lowMemory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverInitSrsAndComputeVkConstMeta =>
      const TaskConstMeta(
        debugName: "init_srs_and_compute_vk",
        argNames: ["circuitBytecode", "srsPath", "lowMemory"],
      );

  @override
  Future<TimedProofResult> crateApiProverProveAndTime({
    required String circuitBytecode,
    required List<int> gridState,
    required String keyHiHex,
    required String keyLoHex,
    required String tHex,
    required String ownerPubkeyHex,
    required String rulesetVersionHex,
    required List<int> vkBytes,
    required bool lowMemory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(circuitBytecode, serializer);
          sse_encode_list_prim_u_8_loose(gridState, serializer);
          sse_encode_String(keyHiHex, serializer);
          sse_encode_String(keyLoHex, serializer);
          sse_encode_String(tHex, serializer);
          sse_encode_String(ownerPubkeyHex, serializer);
          sse_encode_String(rulesetVersionHex, serializer);
          sse_encode_list_prim_u_8_loose(vkBytes, serializer);
          sse_encode_bool(lowMemory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_timed_proof_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverProveAndTimeConstMeta,
        argValues: [
          circuitBytecode,
          gridState,
          keyHiHex,
          keyLoHex,
          tHex,
          ownerPubkeyHex,
          rulesetVersionHex,
          vkBytes,
          lowMemory,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverProveAndTimeConstMeta => const TaskConstMeta(
    debugName: "prove_and_time",
    argNames: [
      "circuitBytecode",
      "gridState",
      "keyHiHex",
      "keyLoHex",
      "tHex",
      "ownerPubkeyHex",
      "rulesetVersionHex",
      "vkBytes",
      "lowMemory",
    ],
  );

  @override
  Future<bool> crateApiProverVerifyProof({
    required List<int> vkBytes,
    required List<int> proofBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(vkBytes, serializer);
          sse_encode_list_prim_u_8_loose(proofBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProverVerifyProofConstMeta,
        argValues: [vkBytes, proofBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProverVerifyProofConstMeta => const TaskConstMeta(
    debugName: "verify_proof",
    argNames: ["vkBytes", "proofBytes"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (int, Uint8List) dco_decode_record_u_32_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_u_32(arr[0]), dco_decode_list_prim_u_8_strict(arr[1]));
  }

  @protected
  TimedProofResult dco_decode_timed_proof_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TimedProofResult(
      proofBytes: dco_decode_list_prim_u_8_strict(arr[0]),
      wallMs: dco_decode_u_64(arr[1]),
      peakRssKb: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, Uint8List) sse_decode_record_u_32_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_32(deserializer);
    var var_field1 = sse_decode_list_prim_u_8_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  TimedProofResult sse_decode_timed_proof_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proofBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_wallMs = sse_decode_u_64(deserializer);
    var var_peakRssKb = sse_decode_u_64(deserializer);
    return TimedProofResult(
      proofBytes: var_proofBytes,
      wallMs: var_wallMs,
      peakRssKb: var_peakRssKb,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_u_32_list_prim_u_8_strict(
    (int, Uint8List) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.$1, serializer);
    sse_encode_list_prim_u_8_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_timed_proof_result(
    TimedProofResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.proofBytes, serializer);
    sse_encode_u_64(self.wallMs, serializer);
    sse_encode_u_64(self.peakRssKb, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
