// SPDX-License-Identifier: GPL-3.0-or-later
//
// basic_spells.dart — GENERATED by scripts/export_basic_spells.dart from the
// authored source library. Do not edit by hand — re-run the script instead
// (see its header and docs/BASIC_SPELLS_PLAN.md §3/§12).
//
// The registry of the five shipped starter spells (docs/BASIC_SPELLS_PLAN.md).
// [isBasicGridAndT] is the ONLY predicate safe to call at a peer-cast trust
// boundary: commitmentHex and t are both proof public inputs (see
// proof_intake.dart's VerifiedSpellOutputs), so checking against verified
// proof outputs never trusts anything the peer merely claims. Do not use
// spellHashHex there — it is a local, off-circuit derivation
// (Poseidon2(commitment, T) via FFI, see SpellAsset.spellHashHex's header)
// and is not itself a proof output.

import 'spell_asset.dart';

/// Bump when the shipped set of basic spells changes (add/remove/replace an
/// entry). Drives re-seeding on existing installs — see basic_spell_seed.dart.
const int kBasicSpellSetVersion = 1;

class BasicSpellEntry {
  const BasicSpellEntry({
    required this.slug,
    required this.name,
    required this.commitmentHex,
    required this.spellHashHex,
    required this.t,
  });

  /// Stable identifier used as both the bundled asset's filename stem and
  /// the seeded SpellAsset.id — stable (unlike a microsecond timestamp) so a
  /// bundled ChapterEntry(spellId:) is portable across installs and so
  /// reseeding recognizes an already-persisted basic without relying on
  /// [spellHashHex] scans.
  final String slug;

  final String name;

  /// Poseidon2(packed_grid) — a proof public input (CIRCUIT_IO.md CIRCUIT_IO 4).
  final String commitmentHex;

  /// Poseidon2(commitment, T), computed off-circuit — used only for local
  /// dedup/display, never at a trust boundary (see header comment above).
  final String spellHashHex;

  /// Active generation count this spell's proof was generated with — a
  /// proof public input (proof_intake.dart ABI field [0]).
  final int t;

  String get assetPath => 'assets/basic_spells/$slug.json';
}

const List<BasicSpellEntry> kBasicSpells = [
  BasicSpellEntry(
    slug: 'basic_firebolt',
    name: "Basic Firebolt",
    commitmentHex:
        '0x21f8c1f0901865f48bd5db27b103d1c0fb5c1fc002c5cb8b96bfba6daca2391e',
    spellHashHex:
        '0x21f89f3db52e62cdd367c8831fc364cff8d8cec40898e44af0549957347bd7f4',
    t: 6,
  ),
  BasicSpellEntry(
    slug: 'basic_speedboost',
    name: "Basic Speedboost",
    commitmentHex:
        '0x0eb58f16f6bc56a1e570082457de777165a0051f3de6b4e893f38a1fad07215d',
    spellHashHex:
        '0x0e60aba776012bd996ddab4f9e6e313e01ee4a2b31fc3b85e2d969439a5ecffa',
    t: 6,
  ),
  BasicSpellEntry(
    slug: 'basic_manabond',
    name: "Basic Manabond",
    commitmentHex:
        '0x2a2f8e7be8cf95b316b4de1d97d8741425e9e04f863a57e21dc1ff112cae85f3',
    spellHashHex:
        '0x1e9dabcfe2272e00ebfe2457443f177391c4afc9f218d593b2f8b047b222675a',
    t: 6,
  ),
  BasicSpellEntry(
    slug: 'basic_earthworks',
    name: "Basic Earthworks",
    commitmentHex:
        '0x28507c37c41c22e002de281b7cde907f1ddbefba591a040c2c8bb3bf35a854b0',
    spellHashHex:
        '0x00ce1c5cc294a79845004f0464ea13e2d4ed0554506fbe46e37ad00180bcec52',
    t: 6,
  ),
  BasicSpellEntry(
    slug: 'basic_windhound',
    name: "Basic Windhound",
    commitmentHex:
        '0x2d587d7e5de727d798b351845299c755fe65c95ef76b9bc0b52bc04aac506194',
    spellHashHex:
        '0x1e053eb1afa520784b7c4acfec9c81c98d6b7a32e8aa6f45eab5b486c6172919',
    t: 23,
  ),
];

String _normHex(String hex) {
  var s = hex.startsWith('0x') || hex.startsWith('0X') ? hex.substring(2) : hex;
  s = s.toLowerCase();
  if (s.length < 64) s = s.padLeft(64, '0');
  return s;
}

/// True iff (commitmentHex, t) matches one of the shipped basic spells.
///
/// This is the ONLY form of this check safe to call against a peer's cast:
/// both commitmentHex and t must come from VERIFIED proof public inputs
/// (proof_intake.dart's VerifiedSpellOutputs.commitmentHex / .t), never from
/// a wire-decoded SpellAsset, which a peer fully controls.
bool isBasicGridAndT(String commitmentHex, int t) {
  final normed = _normHex(commitmentHex);
  return kBasicSpells.any(
    (e) => _normHex(e.commitmentHex) == normed && e.t == t,
  );
}

/// Convenience for local, already-trusted SpellAssets (e.g. library/chapter
/// UI, where the asset came from this device's own disk, not the wire).
/// Cross-checks spellHashHex in addition to (commitment, T); a mismatch
/// means a corrupted or hand-edited asset, so it is treated as NOT basic.
bool isBasicSpell(SpellAsset spell) {
  if (!isBasicGridAndT(spell.commitmentHex, spell.t)) return false;
  final normed = _normHex(spell.spellHashHex);
  return kBasicSpells.any((e) => _normHex(e.spellHashHex) == normed);
}
