// SPDX-License-Identifier: GPL-3.0-or-later
//
// scenery_tile.dart — the terrain textures available to the battle backdrop.
//
// PURELY COSMETIC. Scenery has no gameplay meaning whatsoever: it does not
// affect movement, line of sight, mana, or targeting, and it is never part of
// any hashed or committed state. Real terrain mechanics live in
// lib/battle/models/terrain.dart (TileEffect) and are unrelated to this file.
//
// [atlasIndex] indexes assets/art_pack/terrain/hex_terrain_atlas.png, an 18-cell
// 6x3 atlas generated by scripts/build_hex_terrain.py from the CC0 Screaming
// Brain Studios hex pack. This enum is the canonical index -> terrain mapping;
// see that directory's ATTRIBUTION.md for the atlas geometry.

/// One drawable terrain texture in the scenery atlas.
enum SceneryTile {
  redClay(0, 'Red Clay'),
  dirt(1, 'Bare Earth'),
  mossSoil(2, 'Mire'),
  snow(3, 'Snow'),
  frost(4, 'Rime'),
  ice(5, 'Ice'),
  chalk(6, 'Chalkstone'),
  sand(7, 'Sand'),
  dryGrass(8, 'Dry Grass'),
  charcoal(9, 'Burnt Ground'),
  magma(10, 'Cooling Magma'),
  lava(11, 'Lava'),
  patchGrass(12, 'Scrub'),
  grass(13, 'Grass'),
  forest(14, 'Pinewood'),
  cobble(15, 'Old Paving'),
  shallows(16, 'Shallows'),
  water(17, 'Water');

  const SceneryTile(this.atlasIndex, this.label);

  /// Cell index into the 6x3 atlas, row-major.
  final int atlasIndex;

  /// Human-readable name, shown in the battle HUD's locale line.
  final String label;

  /// Atlas cell column / row.
  int get atlasCol => atlasIndex % atlasColumns;
  int get atlasRow => atlasIndex ~/ atlasColumns;

  /// Tiles the backdrop is allowed to draw.
  ///
  /// Three exclusions, all Soren's call:
  ///
  /// - **Lava and open water** (2026-07-28) — the backdrop only draws ground a
  ///   wizard could be standing on.
  /// - **Snow, rime and ice** (2026-07-28) — they read as out of place against
  ///   the rest of the palette, which is temperate throughout, and they are far
  ///   the brightest tiles in the atlas so they pull the eye off the game
  ///   pieces.
  /// - **Chalk** (2026-08-07) — reserved for [wallTile]. Raised rock now means
  ///   "impassable wall" and nothing else; leaving chalk in the walkable
  ///   palette would put visually identical rock on the ground plane, which is
  ///   exactly the ambiguity the raised walls exist to remove. The elevation
  ///   ladder tops out at a pine treeline instead — see `_kLadder`.
  ///
  /// All seven stay in the enum and in the shipped atlas: they cost nothing to
  /// keep, and a future hazard or seasonal-scenery feature may want them.
  static const Set<SceneryTile> walkable = {
    redClay,
    dirt,
    mossSoil,
    sand,
    dryGrass,
    charcoal,
    patchGrass,
    grass,
    forest,
    cobble,
  };

  /// The terrain an impassable wall is built from.
  ///
  /// Deliberately NOT in [walkable] — see the note there. This is the one place
  /// scenery art is used for something a player can reason about, and it stays
  /// a single named constant so the exception is auditable: everything else in
  /// this file is decoration with no gameplay meaning whatsoever.
  static const SceneryTile wallTile = chalk;

  bool get isWalkable => walkable.contains(this);
}

// ── Atlas geometry ───────────────────────────────────────────────────────────
// Measured from the source sheet, not assumed -- see scripts/build_hex_terrain.py.

/// Atlas grid dimensions, in cells.
const int atlasColumns = 6;
const int atlasRows = 3;

/// One atlas cell, in pixels: a 128-wide flat-top hex face 128 tall, plus a
/// 16px straight-down extrusion that overlaps the tile behind it.
const double atlasCellWidth = 128;
const double atlasCellHeight = 144;

/// Height of the hex face alone (the extrusion is [atlasCellHeight] - this).
const double atlasFaceHeight = 128;

/// Hex-to-hex step in atlas pixel space: columns advance 3/4 of a tile width,
/// rows advance a full face height, and each column step also drops a half row.
const double atlasStepX = atlasCellWidth * 3 / 4; // 96
const double atlasStepY = atlasFaceHeight; // 128
const double atlasColumnDrop = atlasFaceHeight / 2; // 64
