// SPDX-License-Identifier: GPL-3.0-or-later
//
// identity.dart — Dart-side wrapper for the runewright_ffi Poseidon2 bridge.
//
// Mirrors the lib/ffi/prover.dart pattern: hand-written wrapper around the
// generated lib/src/rust/api/identity.dart stub.

// Generated by: flutter_rust_bridge_codegen generate
// ignore: uri_does_not_exist
import '../src/rust/api/identity.dart' as ffi;

/// `Poseidon2(a, b)` -- the same fixed-arity-2 hash the circuit's
/// `owner_pubkey == poseidon2_hash2(key_hi, key_lo)` constraint uses
/// (`circuits/ca_v2_4_tier12/src/main.nr`).
///
/// CLAUDE.md hard invariant 1: never reimplement Poseidon2 in Dart. This is
/// the *only* sanctioned way to compute a Poseidon2 hash from Dart -- it
/// crosses FFI into the real ACVM/Noir-stdlib implementation
/// (`bn254_blackbox_solver`, the same crate the circuit compiles down to),
/// never a second implementation.
///
/// [aHex]/[bHex] and the return value are "0x"-prefixed hex Field strings,
/// matching the convention in `lib/ffi/prover.dart`.
Future<String> poseidon2Hash2(String aHex, String bHex) {
  return ffi.poseidon2Hash2(aHex: aHex, bHex: bHex);
}
