// SPDX-License-Identifier: GPL-3.0-or-later
//
// prover.dart — Dart-side wrapper for the runewright_ffi Rust bridge.
//
// ── CODEGEN NOTE ─────────────────────────────────────────────────────────────
// The imports below reference files generated by flutter_rust_bridge.
// Run this once from the repo root before building:
//
//   cargo install flutter_rust_bridge_codegen
//   flutter_rust_bridge_codegen generate
//
// This produces:
//   lib/src/rust/frb_generated.dart   — RustLib init + type registry
//   lib/src/rust/api/prover.dart      — typed Dart stubs (TimedProofResult etc.)
//
// Until codegen runs the IDE will show red on those imports.  That is expected.
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:developer' as developer;
import 'package:flutter/foundation.dart';

// Generated by: flutter_rust_bridge_codegen generate
// ignore: uri_does_not_exist
import '../src/rust/frb_generated.dart';
// ignore: uri_does_not_exist
import '../src/rust/api/prover.dart' as ffi;

// Re-export so callers only need this file.
// ignore: uri_does_not_exist
export '../src/rust/api/prover.dart' show TimedProofResult;

// ── Lifecycle ─────────────────────────────────────────────────────────────────

/// Call once from main() before any proving.
Future<void> initProverBridge() async {
  await RustLib.init();
}

// ── SRS + VK (combined, thread-safe) ─────────────────────────────────────────

/// Download the SRS and compute the VK in one call.
///
/// This is the correct entry point for the M2 spike and any future code that
/// needs both SRS and VK.  Combining them in one Rust function ensures they
/// run on the same OS thread, which is required because barretenberg's C++
/// stores SRS state in thread-local (or thread-scoped) workspace.  If SRS
/// init and VK computation run on different tokio blocking threads, the VK
/// call throws "Backend error: vector" (std::out_of_range on the empty
/// thread-local SRS vector).
///
/// The Rust layer caches the downloaded SRS bytes and re-pushes them to
/// barretenberg at the start of [proveAndTime] (same fix, no re-download).
///
/// Returns `(numSrsPoints, vkBytes)`.  The VK bytes are stable for a given
/// compiled circuit; persist them across sessions.
Future<(int, Uint8List)> initSrsAndComputeVk(
  String circuitBytecode, {
  String? srsPath,
  bool lowMemory = false,
}) {
  return ffi.initSrsAndComputeVk(
    circuitBytecode: circuitBytecode,
    srsPath: srsPath,
    lowMemory: lowMemory,
  );
}

// ── Legacy separate SRS init (kept for compatibility) ─────────────────────────

/// Initialize SRS only, without computing the VK.
///
/// Does NOT cache SRS bytes in Rust, so subsequent [computeVk] and
/// [proveAndTime] calls may fail with "Backend error: vector" on a different
/// thread.  Prefer [initSrsAndComputeVk] for new code.
///
/// [srsPath] is intentionally **not** forwarded to the Rust layer (always
/// `null` -- always network) even though it's accepted here. Forwarding it
/// was tried and reverted: a dev-machine-local pre-fetched `.dat` file
/// (sized correctly for *one* circuit's unmultiplied point count -- see
/// `init_srs`'s doc comment for why no `* 12` margin) silently breaks if
/// reused for a different tier or a multiplied-margin code path, surfacing
/// as "Backend error: range end index ... out of range" -- a confusing
/// failure with no connection to its actual cause. That fixture file has
/// been deleted (it was a `~/.bb-crs/` dev-machine artifact, never part of
/// the repo) specifically so it can't trap a future session the same way;
/// see docs/M4_findings.md M4.7. Real on-disk SRS caching now lives in
/// [initSrsCached], which downloads-and-saves itself sized to whatever
/// circuit is actually being proven, rather than depending on a
/// pre-fetched file of unverified size. Don't restore this forwarding
/// without addressing that root cause (e.g. keying the cache by circuit
/// size, or validating the file's size against the requested circuit
/// before reading it).
Future<int> initSrs(String circuitBytecode, {String? srsPath}) async {
  return ffi.initSrs(circuitBytecode: circuitBytecode, srsPath: null);
}

/// Initialize SRS with a persistent on-disk cache at [cachePath]: reads
/// from the cache if it already exists there (no network -- this is what
/// makes the second and subsequent inscription on a device work offline);
/// otherwise downloads from crs.aztec.network and writes the cache file for
/// next time. [cachePath] should be a device-local, app-owned file path
/// (e.g. under `path_provider`'s `getApplicationSupportDirectory()`), never
/// the bundled-VK asset path.
///
/// Unlike [initSrs], a download/disk failure here is reported as a normal
/// thrown exception with a clear message (no connection, corrupt cache
/// file) rather than ever crashing the process -- see
/// `ffi/src/api/prover.rs`'s `get_srs_cached` for why that distinction
/// needed an explicit fix on the Rust side.
Future<int> initSrsCached(String circuitBytecode, {required String cachePath}) async {
  return ffi.initSrsCached(circuitBytecode: circuitBytecode, cachePath: cachePath);
}

// ── VK ───────────────────────────────────────────────────────────────────────

/// Compute the VK (re-pushes cached SRS to barretenberg first).
///
/// Requires a prior [initSrsAndComputeVk] call to have populated the SRS cache.
Future<Uint8List> computeVk(String circuitBytecode, {bool lowMemory = false}) {
  return ffi.computeVk(circuitBytecode: circuitBytecode, lowMemory: lowMemory);
}

// ── Prove ─────────────────────────────────────────────────────────────────────

/// Prove the v2.4 CA circuit off the UI thread and return timing data.
///
/// [gridState]    — 469 cell values (0 or 1), flat q×r order.
///                 Index 0 = cell (-12, 0).  See GRID_ORDERING_v2.md.
/// [keyHiHex]/[keyLoHex] — hex Field, the Ed25519-key-half pair (interim zero
///                 keys until the identity module lands).
/// [tHex]          — hex Field, `1 <= T <= tier_max`.
/// [ownerPubkeyHex] — hex Field, `poseidon2_hash2(keyHi, keyLo)`.
/// [rulesetVersionHex] — hex Field, `RULESET_VERSION`.
/// [vkBytes]       — from [computeVk] or a pre-bundled asset.
///
/// Logs `RUNEWRIGHT_PROVE wall_ms=... peak_rss_kb=...` via dart:developer so
/// it appears in `adb logcat -s flutter`.  This is the M2 measurement output.
Future<ffi.TimedProofResult> proveAndTime(
  String circuitBytecode,
  List<int> gridState, {
  required String keyHiHex,
  required String keyLoHex,
  required String tHex,
  required String ownerPubkeyHex,
  required String rulesetVersionHex,
  required Uint8List vkBytes,
  bool lowMemory = false,
}) async {
  assert(gridState.length == 469, 'gridState must be 469 cells');

  final result = await ffi.proveAndTime(
    circuitBytecode: circuitBytecode,
    gridState: Uint8List.fromList(gridState),
    keyHiHex: keyHiHex,
    keyLoHex: keyLoHex,
    tHex: tHex,
    ownerPubkeyHex: ownerPubkeyHex,
    rulesetVersionHex: rulesetVersionHex,
    vkBytes: vkBytes,
    lowMemory: lowMemory,
  );

  _logProveResult(result);
  return result;
}

void _logProveResult(ffi.TimedProofResult r) {
  developer.log(
    'RUNEWRIGHT_PROVE wall_ms=${r.wallMs} peak_rss_kb=${r.peakRssKb} '
    'proof_len=${r.proofBytes.length}',
    name: 'runewright.prover',
    level: 800,
  );

  if (kDebugMode) {
    debugPrint('[runewright.prover] wall=${r.wallMs}ms '
        'rss=${r.peakRssKb}kB proof=${r.proofBytes.length}B');
  }
}

// ── Diagnostic ────────────────────────────────────────────────────────────────

/// Diagnostic: compute VK with Keccak oracle (tests whether the poseidon2
/// lookup-table path is what's broken vs the VK computation in general).
Future<Uint8List> computeVkKeccak(String circuitBytecode, {bool lowMemory = false}) {
  return ffi.computeVkKeccak(
    circuitBytecode: circuitBytecode,
    lowMemory: lowMemory,
  );
}

// ── Verify ────────────────────────────────────────────────────────────────────

/// Verify a proof from [proveAndTime].
Future<bool> verifyProof(Uint8List vkBytes, Uint8List proofBytes) {
  return ffi.verifyProof(vkBytes: vkBytes, proofBytes: proofBytes);
}

// ── Utility ──────────────────────────────────────────────────────────────────

/// Extract base64 bytecode from a Noir circuit JSON string.
Future<String> extractBytecode(String circuitJson) {
  return ffi.extractBytecode(circuitJson: circuitJson);
}
