#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# gen_leyline_codebook_vectors.py — the INDEPENDENT spelling of the Mutable
# Leyline incantation-codebook derivation (docs/LEYLINE_SEED_PLAN.md §4, §5,
# §15; lib/battle/models/leyline_codebook.dart).
#
# ## Why this file exists
#
# The vectors in test/battle/models/leyline_codebook_test.dart must attest the
# SPEC, not the current Dart code's self-consistency. A vector generated by
# running the implementation under test only proves the implementation is
# deterministic — it cannot catch a transcription error, because the error is in
# both the code and the "expected" value. So this script was written from the
# byte layout documented in leyline_codebook.dart's header, by hand, and the
# pinned constants are ITS output. Where the two disagreed, the disagreement was
# resolved against the documented layout before anything was pinned.
#
# It recomputes `leylineConfigHash` from scratch too, rather than accepting the
# hex Dart prints, so the config-hash vectors in leyline_config_test.dart get a
# free second attestation as a side effect.
#
# ## This is a DEV TOOL
#
# Nothing at runtime, in the app, or in `flutter test` shells out to Python.
# Run it by hand when the layout changes (which is a consensus change requiring
# a lexicon bump, so: rarely):
#
#     python3 scripts/gen_leyline_codebook_vectors.py
#
# It prints the corpus as Dart literals ready to paste, and exits non-zero if
# any internal cross-check fails.

import hashlib
import sys

# ── Canonical constants (transcribed from the plan, not from the Dart) ────────

LEYLINE_CONFIG_DOMAIN = "Runewright/Leyline/v1/Config"
INCANTATION_DOMAIN = "Runewright/Leyline/v1/Incantation"
SUMMON_DOMAIN = "Runewright/Leyline/v1/Summon"
ARMOR_DOMAIN = "Runewright/Leyline/v1/Armor"

KEY_ORDER_STREAM = 0x01
EFFECT_ORDER_STREAM = 0x02

# The key alphabet: the circuit's rule indices minus neutral
# (circuits/GRID_ORDERING_v2.md §Rule indices). Name -> canonical wire code.
ALPHABET = [("fire", 1), ("air", 2), ("water", 3), ("earth", 4)]

# The sixteen incantation effects and their pinned consensus codes.
EFFECTS = [
    "damage",
    "barrier",
    "reflections",
    "speedManipulation",
    "statusEffectInteraction",
    "chainInteraction",
    "spellInteraction",
    "fuelTransmutation",
    "tileModification",
    "rangeModification",
    "clouds",
    "artifactsInteraction",
    "illusions",
    "multiplierCycles",
    "haymakerInteraction",
    "divination",
]
EFFECT_CODE = {name: i for i, name in enumerate(EFFECTS)}

DEFAULT_SEED = "universal"


# ── LeylineConfig ────────────────────────────────────────────────────────────

def normalize_seed(raw):
    s = "".join(c for c in raw.lower() if c.isascii() and (c.isalpha() or c.isdigit()))
    return s if s else DEFAULT_SEED


class Config:
    """The canonical leyline configuration, and its hash preimage."""

    def __init__(self, seed, mutable, formula_length, noise_permille, lexicon=1):
        self.seed = seed
        self.mutable = mutable
        self.formula_length = formula_length
        self.noise_permille = noise_permille
        self.lexicon = lexicon
        self._check_canonical()

    def _check_canonical(self):
        if self.lexicon != 1:
            raise ValueError("unsupported lexiconVersion")
        if self.mutable:
            if not 4 <= self.formula_length <= 6:
                raise ValueError("mutable formulaLength outside 4..6")
            if not 0 <= self.noise_permille <= 999:
                raise ValueError("noiseDensityPermille outside 0..999")
        else:
            if self.formula_length != 3 or self.noise_permille != 0:
                raise ValueError("non-canonical ordinary config")

    @property
    def normalized_seed(self):
        return normalize_seed(self.seed)

    @property
    def config_hash_bytes(self):
        # uint8(len(domain)) ‖ ascii(domain) ‖ uint8(lexiconVersion)
        #   ‖ uint8(mutableMagic) ‖ uint8(formulaLength)
        #   ‖ uint16be(noiseDensityPermille)
        #   ‖ uint16be(utf8ByteLength(seed)) ‖ utf8(seed)
        domain = LEYLINE_CONFIG_DOMAIN.encode("ascii")
        seed = self.normalized_seed.encode("utf-8")
        pre = (
            bytes([len(domain)])
            + domain
            + bytes([self.lexicon, 1 if self.mutable else 0, self.formula_length])
            + self.noise_permille.to_bytes(2, "big")
            + len(seed).to_bytes(2, "big")
            + seed
        )
        return hashlib.sha256(pre).digest()

    @property
    def config_hash(self):
        return self.config_hash_bytes.hex()

    @property
    def display(self):
        return f"{self.seed} {self.formula_length}" if self.mutable else self.seed


# ── The scoring primitive ────────────────────────────────────────────────────

def stream_score(domain_tag, config, stream_tag, payload):
    # uint8(len(domain)) ‖ ascii(domain) ‖ uint8(lexiconVersion)
    #   ‖ configHash[32] ‖ uint8(streamTag) ‖ uint8(len(payload)) ‖ payload
    domain = domain_tag.encode("ascii")
    pre = (
        bytes([len(domain)])
        + domain
        + bytes([config.lexicon])
        + config.config_hash_bytes
        + bytes([stream_tag, len(payload)])
        + bytes(payload)
    )
    return hashlib.sha256(pre).digest()


# ── Derivation ───────────────────────────────────────────────────────────────

def noise_key_count(total, permille):
    """Round-half-up on the NOISE count, integer arithmetic throughout."""
    return (total * permille + 500) // 1000


def enumerate_keys(key_length):
    """Base-4 over ALPHABET, most significant element first."""
    keys = []
    for index in range(4 ** key_length):
        digits = []
        remaining = index
        for _ in range(key_length):
            digits.append(remaining % 4)
            remaining //= 4
        keys.append(tuple(ALPHABET[d] for d in reversed(digits)))
    return keys


def effect_order(config, domain_tag=INCANTATION_DOMAIN):
    scored = [
        (stream_score(domain_tag, config, EFFECT_ORDER_STREAM, [EFFECT_CODE[e]]),
         EFFECT_CODE[e], e)
        for e in EFFECTS
    ]
    scored.sort(key=lambda t: (t[0], t[1]))
    return [t[2] for t in scored]


def ordered_keys(config, key_length, domain_tag=INCANTATION_DOMAIN):
    keys = enumerate_keys(key_length)
    scored = []
    for key in keys:
        payload = [code for (_, code) in key]
        scored.append(
            (stream_score(domain_tag, config, KEY_ORDER_STREAM, payload),
             bytes(payload), key)
        )
    scored.sort(key=lambda t: (t[0], t[1]))
    return [t[2] for t in scored]


def derive(config, domain_tag=INCANTATION_DOMAIN):
    if not config.mutable:
        raise ValueError("ordinary leylines have no derived codebook")
    key_length = config.formula_length - 1
    total = 4 ** key_length
    order = ordered_keys(config, key_length, domain_tag)
    noise = noise_key_count(total, config.noise_permille)
    meaningful = total - noise
    effects = effect_order(config, domain_tag)
    meanings = {}
    for rank, key in enumerate(order):
        meanings[key] = effects[rank % 16] if rank < meaningful else None
    return {
        "config": config,
        "keyLength": key_length,
        "total": total,
        "meaningful": meaningful,
        "noise": noise,
        "orderedKeys": order,
        "effectOrder": effects,
        "meanings": meanings,
    }


# ── Reporting ────────────────────────────────────────────────────────────────

def key_str(key):
    return "-".join(name for (name, _) in key)


def dart_key(key):
    return "[" + ", ".join(f"BorderZone.{name}" for (name, _) in key) + "]"


def report(book, label, prefix=6):
    c = book["config"]
    order = book["orderedKeys"]
    print(f"── {label} ──")
    print(f"  display           {c.display}")
    print(f"  configHash        {c.config_hash}")
    print(f"  keyLength         {book['keyLength']}")
    print(f"  totalKeyCount     {book['total']}")
    print(f"  meaningfulCount   {book['meaningful']}")
    print(f"  noiseCount        {book['noise']}")
    print(f"  effectOrder       {', '.join(book['effectOrder'])}")
    print(f"  first {prefix} ordered keys:")
    for i in range(min(prefix, len(order))):
        m = book["meanings"][order[i]]
        print(f"    [{i}] {dart_key(order[i]):<70} -> {m or 'NOISE'}")
    noise_keys = [k for k in order if book["meanings"][k] is None]
    print(f"  first {prefix} noise keys:")
    for k in noise_keys[:prefix]:
        print(f"    {dart_key(k)}")
    counts = {}
    for k in order:
        m = book["meanings"][k]
        if m is not None:
            counts[m] = counts.get(m, 0) + 1
    per = {e: counts.get(e, 0) for e in EFFECTS}
    print("  per-effect counts (declaration order):")
    print("    " + ", ".join(str(per[e]) for e in EFFECTS))
    spread = max(per.values()) - min(per.values())
    print(f"  count spread      {spread}")
    print()
    return per


def main():
    failures = []

    def check(cond, msg):
        if not cond:
            failures.append(msg)
            print(f"  !! CHECK FAILED: {msg}")

    print("=" * 78)
    print("LeylineConfig hashes (independent recomputation)")
    print("=" * 78)
    for label, cfg in [
        ("ordinaryDefault", Config("universal", False, 3, 0)),
        ("ordinary('rivendell')", Config("rivendell", False, 3, 0)),
        ("ordinary('glassmountain')", Config("glassmountain", False, 3, 0)),
        ("mutable('rivendell', 4, 500)", Config("rivendell", True, 4, 500)),
        ("mutable('rivendell', 5, 500)", Config("rivendell", True, 5, 500)),
    ]:
        print(f"  {label:<32} {cfg.config_hash}")
    print()

    print("=" * 78)
    print("§5 ratified count table")
    print("=" * 78)
    for length, total, expected in [(4, 64, 32), (5, 256, 128), (6, 1024, 512)]:
        n = noise_key_count(total, 500)
        print(f"  L={length}  total={total:<5} noise={n:<5} meaningful={total - n:<5} "
              f"per effect={(total - n) / 16}")
        check(total - n == expected, f"L={length} meaningful {total - n} != {expected}")
    print()

    print("=" * 78)
    print("Codebooks — canonical seed 'rivendell', 500‰")
    print("=" * 78)
    for length in (4, 5, 6):
        book = derive(Config("rivendell", True, length, 500))
        per = report(book, f"rivendell {length}, 500‰")
        check(all(v == book["meaningful"] // 16 for v in per.values()),
              f"L={length} per-effect counts not exactly even")

    print("=" * 78)
    print("0‰ sanity — a pure permutation, no noise")
    print("=" * 78)
    book = derive(Config("rivendell", True, 4, 0))
    per = report(book, "rivendell 4, 0‰")
    check(book["noise"] == 0, "0‰ produced noise")
    check(book["meaningful"] == 64, "0‰ meaningful != 64")
    check(max(per.values()) - min(per.values()) == 0, "0‰ counts uneven")

    print("=" * 78)
    print("Non-divisible — 333‰ at L=4 (audit §5.2 item 3)")
    print("=" * 78)
    book = derive(Config("rivendell", True, 4, 333))
    per = report(book, "rivendell 4, 333‰")
    check(book["noise"] == 21, f"333‰ noise {book['noise']} != 21")
    check(book["meaningful"] == 43, f"333‰ meaningful {book['meaningful']} != 43")
    check(max(per.values()) - min(per.values()) == 1, "333‰ spread != 1")
    extra = [e for e in EFFECTS if per[e] == 3]
    print(f"  effects with the extra key: {', '.join(extra)}")
    print(f"  = the first {book['meaningful'] % 16} of the derived effect order: "
          f"{book['effectOrder'][:book['meaningful'] % 16] == sorted(extra, key=lambda e: book['effectOrder'].index(e))}")
    print()

    print("=" * 78)
    print("Rounding edge cases")
    print("=" * 78)
    for total, permille in [(64, 0), (64, 1), (64, 7), (64, 8), (64, 500),
                            (64, 999), (256, 333), (1024, 333), (1024, 999)]:
        n = noise_key_count(total, permille)
        print(f"  total={total:<5} permille={permille:<5} noise={n:<5} meaningful={total - n}")
    print("  NOTE: 999‰ at L=4 rounds to 64 noise / 0 meaningful — reachable,")
    print("        deliberately not clamped, flagged for ruling.")
    print()

    print("=" * 78)
    print("Domain separation — same config, different tag")
    print("=" * 78)
    cfg = Config("rivendell", True, 4, 500)
    inc = ordered_keys(cfg, 3, INCANTATION_DOMAIN)
    summ = ordered_keys(cfg, 3, SUMMON_DOMAIN)
    arm = ordered_keys(cfg, 3, ARMOR_DOMAIN)
    print(f"  incantation[0]  {key_str(inc[0])}")
    print(f"  summon[0]       {key_str(summ[0])}")
    print(f"  armor[0]        {key_str(arm[0])}")
    check(inc != summ and inc != arm and summ != arm, "domains produced equal orders")
    print(f"  incantation effectOrder[0]  {effect_order(cfg, INCANTATION_DOMAIN)[0]}")
    print(f"  summon      effectOrder[0]  {effect_order(cfg, SUMMON_DOMAIN)[0]}")
    print()

    print("=" * 78)
    print("Normalization — equivalent spellings")
    print("=" * 78)
    base = derive(Config("rivendell", True, 4, 500))
    for spelling in ["Rivendell", "RIVENDELL", "  rivendell  ", "Rivendell!", "ri-ven-dell"]:
        other = derive(Config(spelling, True, 4, 500))
        same = other["orderedKeys"] == base["orderedKeys"] and \
            other["meanings"] == base["meanings"]
        print(f"  {spelling!r:<20} -> same codebook: {same}")
        check(same, f"{spelling!r} did not normalize to the same codebook")
    print()

    print("=" * 78)
    print("Seed / length / density separation")
    print("=" * 78)
    a = derive(Config("rivendell", True, 4, 500))
    b = derive(Config("glassmountain", True, 4, 500))
    c = derive(Config("rivendell", True, 4, 400))
    check(a["orderedKeys"] != b["orderedKeys"], "two seeds shared a key order")
    check(a["orderedKeys"] != c["orderedKeys"], "two densities shared a key order")
    print(f"  rivendell vs glassmountain differ: {a['orderedKeys'] != b['orderedKeys']}")
    print(f"  500‰ vs 400‰ differ:               {a['orderedKeys'] != c['orderedKeys']}")
    print()

    if failures:
        print(f"FAILED: {len(failures)} check(s)")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("All internal cross-checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
