#!/usr/bin/env python3
"""Generate Noir grid topology constants for the radius=12 hex grid.

Usage: python3 scripts/gen_grid_constants.py > circuits/ca_natural_v2/src/constants.nr
"""

RADIUS = 12
N = 469  # 1 + 3*12*13

# --- Cell enumeration (matches HexGrid(12) constructor in Dart) ---

def all_cells():
    cells = []
    for q in range(-RADIUS, RADIUS + 1):
        r1 = max(-RADIUS, -q - RADIUS)
        r2 = min(RADIUS, -q + RADIUS)
        for r in range(r1, r2 + 1):
            cells.append((q, r))
    return cells

CELLS = all_cells()
assert len(CELLS) == N, f"Expected {N}, got {len(CELLS)}"

CELL_INDEX = {c: i for i, c in enumerate(CELLS)}

# Six directions matching HexGrid.directions in Dart
DIRS = [(1, 0), (1, -1), (0, -1), (-1, 0), (-1, 1), (0, 1)]

def is_border(q, r):
    return max(abs(q), abs(r), abs(q + r)) == RADIUS

def neighbor_indices(q, r):
    result = []
    for dq, dr in DIRS:
        nb = (q + dq, r + dr)
        result.append(CELL_INDEX.get(nb, N))  # N = sentinel for off-grid
    return result

# --- Border zone assignment (radius=12 specific, matches BorderZones.dart) ---

def ring_clockwise(r):
    """Enumerate ring-r cells clockwise from (0, -r), matching _ringClockwise in Dart."""
    sides = [
        ((0, -1), ( 1,  0)),  # top → top-right
        ((1, -1), ( 0,  1)),  # top-right → right
        ((1,  0), (-1,  1)),  # right → bottom-right
        ((0,  1), (-1,  0)),  # bottom-right → bottom-left
        ((-1, 1), ( 0, -1)),  # bottom-left → left
        ((-1, 0), ( 1, -1)),  # left → top
    ]
    coords = []
    for (cq, cr), (dq, dr) in sides:
        q, row = cq * r, cr * r
        for _ in range(r):
            coords.append((q, row))
            q += dq
            row += dr
    return coords

def border_zones():
    ring = ring_clockwise(RADIUS)
    n = len(ring)
    # Match BorderZones._compute in Dart:
    #   start at ring[3*RADIUS] = (0, RADIUS) (bottom vertex)
    #   traverse counter-clockwise (decrement ring index, wrap)
    #   segments: water(18) | air(18) | fire(18) | earth(18)
    # Zone indices: 0=none, 1=fire, 2=air, 3=water, 4=earth
    start = 3 * RADIUS
    segs = [(3, 18), (2, 18), (1, 18), (4, 18)]  # water, air, fire, earth
    zm = {}
    i = 0
    for zone, cnt in segs:
        for _ in range(cnt):
            zm[ring[(start - i + n) % n]] = zone
            i += 1
    assert i == 6 * RADIUS, f"Expected {6*RADIUS} border cells, assigned {i}"
    return zm

BZ = border_zones()

# --- Verify ---
border_cells = [(q, r) for q, r in CELLS if is_border(q, r)]
assert len(border_cells) == 72
zone_counts = {}
for c in border_cells:
    z = BZ.get(c, 0)
    zone_counts[z] = zone_counts.get(z, 0) + 1
assert zone_counts == {1: 18, 2: 18, 3: 18, 4: 18}, f"Zone counts: {zone_counts}"

# --- Generate Noir source ---

lines = []
lines.append("// Auto-generated by scripts/gen_grid_constants.py — DO NOT EDIT BY HAND\n")
lines.append("// Grid: hex axial coords, radius=12, vertex-down orientation.\n")
lines.append("// Cell ordering: q from -12 to +12, r from max(-12,-q-12) to min(12,-q+12).\n\n")

lines.append(f"pub global N: u32 = {N}; // total cells (rings 0-12)\n")
lines.append(f"pub global SENTINEL: u32 = {N}; // off-grid neighbor marker\n\n")

# IS_BORDER
bvals = ["true" if is_border(q, r) else "false" for q, r in CELLS]
lines.append("pub global IS_BORDER: [bool; 469] = [\n    ")
lines.append(", ".join(bvals))
lines.append("\n];\n\n")

# NEIGHBORS
lines.append("pub global NEIGHBORS: [[u32; 6]; 469] = [\n")
for q, r in CELLS:
    nbs = neighbor_indices(q, r)
    lines.append(f"    [{', '.join(str(n) for n in nbs)}],\n")
lines.append("];\n\n")

# BORDER_ZONE: 0=none, 1=fire, 2=air, 3=water, 4=earth
zvals = [str(BZ.get((q, r), 0)) for q, r in CELLS]
lines.append("pub global BORDER_ZONE: [u32; 469] = [\n    ")
lines.append(", ".join(zvals))
lines.append("\n];\n")

print("".join(lines))

# --- Also print test grid helper (alive cell indices for Prover.toml) ---
import sys
if "--test-grid" in sys.argv:
    # A non-trivial test pattern: clusters near fire (top), earth (bottom), water (sides)
    # Fire zone direction: top, q near 0, r negative
    alive_coords = [
        # Near-top cluster (heads toward fire zone)
        (0, -5), (1, -5), (-1, -4), (0, -4),
        # Near-bottom cluster (heads toward earth zone)
        (0, 5), (1, 4), (-1, 5), (0, 4),
        # Right-side cluster (heads toward water zone)
        (4, -2), (4, -1), (3, -2),
        # Left-side cluster (heads toward water zone)
        (-4, 2), (-4, 1), (-3, 2),
        # Center ring (neutral activity)
        (2, -1), (2, 0), (1, 1), (-1, 1), (-2, 0), (-1, -1),
    ]
    grid = [0] * N
    for coord in alive_coords:
        idx = CELL_INDEX.get(coord)
        assert idx is not None, f"Coord {coord} not in grid"
        assert not is_border(*coord), f"Coord {coord} is on border (should start empty)"
        grid[idx] = 1
    print(f"\n// Test grid: {sum(grid)} alive cells")
    print(f"// grid_state = [{', '.join(str(v) for v in grid)}]")
