#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# gen_leyline_pattern_vectors.py — the INDEPENDENT spelling of the Mutable
# Leyline SUMMON and ARMOR pattern-dictionary derivation
# (docs/LEYLINE_SEED_PLAN.md §8, §9, §15;
#  docs/MUTABLE_LEYLINES_IMPLEMENTATION_AUDIT.md R-8;
#  lib/battle/models/leyline_pattern_codebook.dart).
#
# ## Why this file exists
#
# Same reason as its sibling `gen_leyline_codebook_vectors.py`: the vectors in
# test/battle/models/leyline_pattern_codebook_test.dart must attest the SPEC,
# not the Dart implementation's self-consistency. A vector generated by running
# the code under test only proves the code is deterministic. So this script was
# written from the byte layout ruled in R-8, by hand, and the pinned constants
# are ITS output.
#
# It recomputes `leylineTraditionHash` from scratch too, so the tradition-hash
# vectors in leyline_config_test.dart get a second independent attestation.
#
# ## What is DIFFERENT from the incantation codebook (R-8, deliberately)
#
#   * the key space is the 256 four-element PATTERNS, not the 4^(L-1) tails —
#     `formulaLength` is the Incantation grammar's length and is not a generic
#     pattern length;
#   * the binding hash is the leyline's TRADITION hash, which excludes
#     `formulaLength` and `noiseDensityPermille`, so `rivendell 4/5/6` share one
#     summon dictionary and one armor dictionary;
#   * the meaningful count is the domain's ordinary cardinality (8 summon
#     abilities, 7 armor keywords), NOT a noise-density proportion — these are
#     sliding-window languages and half of all windows meaning something would
#     be a different game;
#   * there is no noise VALUE: an unrecognised pattern is simply absent from the
#     dictionary, because a sliding window that matches nothing is the ordinary
#     case, not a decoded meaning.
#
# ## This is a DEV TOOL
#
# Nothing at runtime shells out to Python. Run it by hand when the layout
# changes (a consensus change requiring a lexicon bump, so: rarely):
#
#     python3 scripts/gen_leyline_pattern_vectors.py

import hashlib
import sys

# ── Canonical constants (transcribed from the plan and R-8, not from the Dart) ─

TRADITION_DOMAIN = "Runewright/Leyline/v1/Tradition"
INCANTATION_DOMAIN = "Runewright/Leyline/v1/Incantation"
SUMMON_DOMAIN = "Runewright/Leyline/v1/Summon"
ARMOR_DOMAIN = "Runewright/Leyline/v1/Armor"

PATTERN_ORDER_STREAM = 0x11
OUTPUT_ORDER_STREAM = 0x12

# The key alphabet: the circuit's rule indices minus neutral
# (circuits/GRID_ORDERING_v2.md §Rule indices). Name -> canonical wire code.
ALPHABET = [("fire", 1), ("air", 2), ("water", 3), ("earth", 4)]
INITIAL = {"fire": "F", "air": "A", "water": "W", "earth": "E"}

# Both domains match four-element windows. NOT LeylineConfig.formulaLength.
PATTERN_LENGTH = 4

# The eight summon abilities and their pinned consensus codes (declaration
# order in creature_spec.dart, frozen).
SUMMON_ABILITIES = [
    "flying",
    "cleave",
    "big",
    "morphic",
    "charger",
    "stealthy",
    "muddy",
    "moltenCarapace",
]

# The seven armor keywords and their pinned consensus codes (declaration order
# in certified_armor.dart, frozen). Morphic is deliberately absent.
ARMOR_KEYWORDS = [
    "flying",
    "cleave",
    "charger",
    "muddy",
    "moltenCarapace",
    "stealthy",
    "anchored",
]

# The ORDINARY patterns, for the invariance cross-checks only. Never an input to
# a derivation.
ORDINARY_SUMMON = {
    "flying": "AAAA",
    "cleave": "FFFF",
    "big": "EEEE",
    "morphic": "WWWW",
    "charger": "FAFA",
    "stealthy": "AWAW",
    "muddy": "WEWE",
    "moltenCarapace": "EFEF",
}
ORDINARY_ARMOR = {
    "flying": "AAAA",
    "cleave": "FFFF",
    "charger": "FAFA",
    "muddy": "WEWE",
    "moltenCarapace": "EFEF",
    "stealthy": "AWAW",
    "anchored": "EEEE",
}

DEFAULT_SEED = "universal"


# ── LeylineConfig — the tradition projection ─────────────────────────────────

def normalize_seed(raw):
    s = "".join(c for c in raw.lower() if c.isascii() and (c.isalpha() or c.isdigit()))
    return s if s else DEFAULT_SEED


class Config:
    """Only the fields the TRADITION hash binds, plus the two it deliberately
    does not (kept so the script can prove they do not participate)."""

    def __init__(self, seed, mutable, formula_length, noise_permille, lexicon=1):
        self.seed = seed
        self.mutable = mutable
        self.formula_length = formula_length
        self.noise_permille = noise_permille
        self.lexicon = lexicon

    @property
    def normalized_seed(self):
        return normalize_seed(self.seed)

    @property
    def tradition_hash_bytes(self):
        # uint8(len(domain)) ‖ ascii(domain) ‖ uint8(lexiconVersion)
        #   ‖ uint8(mutableMagic)
        #   ‖ uint16be(utf8ByteLength(seed)) ‖ utf8(seed)
        #
        # formulaLength and noiseDensityPermille are ABSENT, which is the whole
        # point: they are Incantation-grammar controls (R-8).
        domain = TRADITION_DOMAIN.encode("ascii")
        seed = self.normalized_seed.encode("utf-8")
        pre = (
            bytes([len(domain)])
            + domain
            + bytes([self.lexicon, 1 if self.mutable else 0])
            + len(seed).to_bytes(2, "big")
            + seed
        )
        return hashlib.sha256(pre).digest()

    @property
    def tradition_hash(self):
        return self.tradition_hash_bytes.hex()

    @property
    def display(self):
        return f"{self.seed} {self.formula_length}" if self.mutable else self.seed


# ── The scoring primitive ────────────────────────────────────────────────────

def tradition_stream_score(domain_tag, config, stream_tag, payload):
    # uint8(len(domain)) ‖ ascii(domain) ‖ uint8(lexiconVersion)
    #   ‖ traditionHash[32] ‖ uint8(streamTag) ‖ uint8(len(payload)) ‖ payload
    domain = domain_tag.encode("ascii")
    pre = (
        bytes([len(domain)])
        + domain
        + bytes([config.lexicon])
        + config.tradition_hash_bytes
        + bytes([stream_tag, len(payload)])
        + bytes(payload)
    )
    return hashlib.sha256(pre).digest()


# ── Derivation ───────────────────────────────────────────────────────────────

def enumerate_patterns(length=PATTERN_LENGTH):
    """Base-4 over ALPHABET, most significant element first."""
    out = []
    for index in range(4 ** length):
        digits = []
        remaining = index
        for _ in range(length):
            digits.append(remaining % 4)
            remaining //= 4
        out.append(tuple(ALPHABET[d] for d in reversed(digits)))
    return out


def output_order(config, domain_tag, vocabulary):
    codes = {name: i for i, name in enumerate(vocabulary)}
    scored = [
        (
            tradition_stream_score(domain_tag, config, OUTPUT_ORDER_STREAM, [codes[v]]),
            codes[v],
            v,
        )
        for v in vocabulary
    ]
    scored.sort(key=lambda t: (t[0], t[1]))
    return [t[2] for t in scored]


def ordered_patterns(config, domain_tag):
    scored = []
    for pattern in enumerate_patterns():
        payload = [code for (_, code) in pattern]
        scored.append(
            (
                tradition_stream_score(
                    domain_tag, config, PATTERN_ORDER_STREAM, payload
                ),
                bytes(payload),
                pattern,
            )
        )
    scored.sort(key=lambda t: (t[0], t[1]))
    return [t[2] for t in scored]


def derive(config, domain_tag, vocabulary):
    """The complete dictionary: pattern -> output name, or absent (inert)."""
    if not config.mutable:
        raise ValueError("ordinary leylines have no derived pattern dictionary")
    order = ordered_patterns(config, domain_tag)
    outputs = output_order(config, domain_tag, vocabulary)
    meaningful = len(vocabulary)
    meanings = {}
    for rank, pattern in enumerate(order):
        if rank < meaningful:
            meanings[pattern] = outputs[rank % len(outputs)]
    return {
        "config": config,
        "domain": domain_tag,
        "orderedPatterns": order,
        "outputOrder": outputs,
        "meanings": meanings,
        "meaningfulCount": meaningful,
        "totalCount": len(order),
    }


# ── Reporting ────────────────────────────────────────────────────────────────

def initials(pattern):
    return "".join(INITIAL[name] for (name, _) in pattern)


def dart_pattern(pattern):
    return "[" + ", ".join(f"BorderZone.{name}" for (name, _) in pattern) + "]"


def report(book, label):
    c = book["config"]
    print(f"── {label} ──")
    print(f"  display              {c.display}")
    print(f"  traditionHash        {c.tradition_hash}")
    print(f"  totalPatternCount    {book['totalCount']}")
    print(f"  meaningfulCount      {book['meaningfulCount']}")
    print(f"  outputOrder          {', '.join(book['outputOrder'])}")
    print("  the complete meaningful set, in derived rank order:")
    for rank, pattern in enumerate(book["orderedPatterns"][: book["meaningfulCount"]]):
        print(
            f"    [{rank}] {initials(pattern):<6} {dart_pattern(pattern):<66} "
            f"-> {book['meanings'][pattern]}"
        )
    print("  first 4 inert patterns (rank order):")
    for pattern in book["orderedPatterns"][
        book["meaningfulCount"] : book["meaningfulCount"] + 4
    ]:
        print(f"    {initials(pattern):<6} {dart_pattern(pattern)}")
    print()
    return book


def main():
    failures = []

    def check(cond, msg):
        if not cond:
            failures.append(msg)
            print(f"  !! CHECK FAILED: {msg}")

    print("=" * 78)
    print("Tradition hashes (independent recomputation)")
    print("=" * 78)
    for label, cfg in [
        ("ordinaryDefault", Config("universal", False, 3, 0)),
        ("ordinary('rivendell')", Config("rivendell", False, 3, 0)),
        ("mutable('rivendell', 4, 500)", Config("rivendell", True, 4, 500)),
        ("mutable('rivendell', 5, 500)", Config("rivendell", True, 5, 500)),
        ("mutable('rivendell', 4, 333)", Config("rivendell", True, 4, 333)),
        ("mutable('glassmountain', 4, 500)", Config("glassmountain", True, 4, 500)),
    ]:
        print(f"  {label:<34} {cfg.tradition_hash}")
    print()

    print("=" * 78)
    print("Ordinary cardinality — the count the mutable dictionaries preserve")
    print("=" * 78)
    for name, table, vocab in [
        ("summon", ORDINARY_SUMMON, SUMMON_ABILITIES),
        ("armor", ORDINARY_ARMOR, ARMOR_KEYWORDS),
    ]:
        print(f"  {name:<8} vocabulary {len(vocab):<3} distinct patterns "
              f"{len(set(table.values()))}")
        check(sorted(table) == sorted(vocab), f"{name} table/vocabulary mismatch")
        check(
            len(set(table.values())) == len(vocab),
            f"{name} does not have exactly one pattern per output",
        )
        for p in table.values():
            check(len(p) == PATTERN_LENGTH, f"{name} pattern {p} is not 4 long")
    print(f"  key space  4^{PATTERN_LENGTH} = {4 ** PATTERN_LENGTH}")
    print()

    print("=" * 78)
    print("SUMMON dictionaries")
    print("=" * 78)
    riv4_s = report(
        derive(Config("rivendell", True, 4, 500), SUMMON_DOMAIN, SUMMON_ABILITIES),
        "rivendell 4, 500‰  ->  Summon",
    )
    glass_s = report(
        derive(Config("glassmountain", True, 4, 500), SUMMON_DOMAIN, SUMMON_ABILITIES),
        "glassmountain 4, 500‰  ->  Summon",
    )

    print("=" * 78)
    print("ARMOR dictionaries")
    print("=" * 78)
    riv4_a = report(
        derive(Config("rivendell", True, 4, 500), ARMOR_DOMAIN, ARMOR_KEYWORDS),
        "rivendell 4, 500‰  ->  Armor",
    )
    glass_a = report(
        derive(Config("glassmountain", True, 4, 500), ARMOR_DOMAIN, ARMOR_KEYWORDS),
        "glassmountain 4, 500‰  ->  Armor",
    )

    print("=" * 78)
    print("Incantation-grammar independence (R-8's config-field projection)")
    print("=" * 78)
    base = Config("rivendell", True, 4, 500)
    for label, other in [
        ("formulaLength 5", Config("rivendell", True, 5, 500)),
        ("formulaLength 6", Config("rivendell", True, 6, 500)),
        ("noiseDensity 333‰", Config("rivendell", True, 4, 333)),
        ("noiseDensity 0‰", Config("rivendell", True, 4, 0)),
    ]:
        s = derive(other, SUMMON_DOMAIN, SUMMON_ABILITIES)
        a = derive(other, ARMOR_DOMAIN, ARMOR_KEYWORDS)
        same = (
            s["meanings"] == riv4_s["meanings"] and a["meanings"] == riv4_a["meanings"]
        )
        print(f"  {label:<22} -> same summon+armor dictionaries: {same}")
        check(same, f"{label} rekeyed a pattern dictionary")
    print(f"  (base tradition hash {base.tradition_hash[:16]}…)")
    print()

    print("=" * 78)
    print("Seed separation")
    print("=" * 78)
    check(
        riv4_s["meanings"] != glass_s["meanings"], "two seeds shared a summon dictionary"
    )
    check(
        riv4_a["meanings"] != glass_a["meanings"], "two seeds shared an armor dictionary"
    )
    print(f"  summon rivendell vs glassmountain differ: "
          f"{riv4_s['meanings'] != glass_s['meanings']}")
    print(f"  armor  rivendell vs glassmountain differ: "
          f"{riv4_a['meanings'] != glass_a['meanings']}")
    print()

    print("=" * 78)
    print("Domain separation — one tradition, three dictionaries")
    print("=" * 78)
    inc = ordered_patterns(base, INCANTATION_DOMAIN)
    summ = ordered_patterns(base, SUMMON_DOMAIN)
    arm = ordered_patterns(base, ARMOR_DOMAIN)
    print(f"  incantation-tagged rank 0  {initials(inc[0])}")
    print(f"  summon      rank 0         {initials(summ[0])}")
    print(f"  armor       rank 0         {initials(arm[0])}")
    check(
        inc != summ and inc != arm and summ != arm,
        "two domain tags produced the same pattern order",
    )
    # The two live domains share a vocabulary of names; prove the shared names
    # do not share patterns.
    shared = set(SUMMON_ABILITIES) & set(ARMOR_KEYWORDS)
    s_by_name = {v: k for k, v in riv4_s["meanings"].items()}
    a_by_name = {v: k for k, v in riv4_a["meanings"].items()}
    collisions = [n for n in shared if s_by_name[n] == a_by_name[n]]
    print(f"  names in both domains: {len(shared)}; sharing a pattern: "
          f"{len(collisions)} {collisions}")
    print()

    print("=" * 78)
    print("Ordinary-pattern displacement — what a player must relearn")
    print("=" * 78)
    for name, book, table in [
        ("summon", riv4_s, ORDINARY_SUMMON),
        ("armor", riv4_a, ORDINARY_ARMOR),
    ]:
        moved, kept, inert = [], [], []
        by_initials = {initials(p): m for p, m in book["meanings"].items()}
        for output, pat in sorted(table.items()):
            now = by_initials.get(pat)
            if now is None:
                inert.append(f"{pat}({output})")
            elif now == output:
                kept.append(f"{pat}({output})")
            else:
                moved.append(f"{pat}: {output} -> {now}")
        print(f"  {name}: {len(inert)} ordinary patterns now inert, "
              f"{len(moved)} remapped, {len(kept)} unchanged")
        for line in inert:
            print(f"    inert    {line}")
        for line in moved:
            print(f"    remapped {line}")
        for line in kept:
            print(f"    kept     {line}")
    print()

    print("=" * 78)
    print("Normalization — equivalent spellings")
    print("=" * 78)
    for spelling in ["Rivendell", "RIVENDELL", "  rivendell  ", "Rivendell!", "ri-ven-dell"]:
        other = derive(
            Config(spelling, True, 4, 500), SUMMON_DOMAIN, SUMMON_ABILITIES
        )
        same = other["meanings"] == riv4_s["meanings"]
        print(f"  {spelling!r:<20} -> same summon dictionary: {same}")
        check(same, f"{spelling!r} did not normalize to the same dictionary")
    print()

    if failures:
        print(f"FAILED: {len(failures)} check(s)")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("All internal cross-checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
