// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `poseidon2_hash2(a, b)` matching the circuit's helper of the same name
/// (`circuits/ca_v2_4_tier12/src/main.nr`) bit-for-bit -- same fixed IV,
/// same arity-2-padded-to-4 state, same permutation.
///
/// `a_hex`/`b_hex` and the return value are "0x"-prefixed hex Field strings,
/// the same convention used throughout `api::prover`.
Future<String> poseidon2Hash2({required String aHex, required String bHex}) =>
    RustLib.instance.api.crateApiIdentityPoseidon2Hash2(aHex: aHex, bHex: bHex);
