// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_srs_cached`, `read_peak_rss_kb`, `reinit_srs_on_thread`, `set_hardware_concurrency_workaround`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedSrs`

/// Download (or read) the SRS and compute the UltraHonk VK in one blocking call.
///
/// This replaces the old `init_srs` + `compute_vk` two-step sequence.
/// Combining them in one function ensures both operations run on the same
/// OS thread, which is required for barretenberg's thread-scoped SRS state
/// to be visible during VK computation.
///
/// The downloaded SRS bytes are cached in `SRS_CACHE` for re-use by
/// `prove_and_time` (which re-pushes them to barretenberg on its thread
/// without re-downloading).
///
/// `srs_path = None`  → network download from crs.aztec.network (~128 MB for T=12).
/// `srs_path = Some(p)` → read from local .dat file at path `p`.
///
/// Returns `(num_srs_points, vk_bytes)`.
Future<(int, Uint8List)> initSrsAndComputeVk({
  required String circuitBytecode,
  String? srsPath,
  required bool lowMemory,
}) => RustLib.instance.api.crateApiProverInitSrsAndComputeVk(
  circuitBytecode: circuitBytecode,
  srsPath: srsPath,
  lowMemory: lowMemory,
);

/// Download (or read) the SRS and cache it — without computing the VK.
///
/// Use this when the VK is loaded from a pre-bundled asset, bypassing the
/// AArch64-specific `circuit_compute_vk` bug in the current barretenberg binary.
/// Caches SRS bytes in `SRS_CACHE` so `prove_and_time` can re-push them on its
/// thread without re-downloading.
///
/// No oversizing multiplier here (unlike `init_srs_and_compute_vk`'s `* 12`):
/// that margin exists only to give on-device `circuit_compute_vk` extra room,
/// which this bundled-VK path skips entirely. Confirmed empirically (M3.4) —
/// `setup_srs_from_bytecode`'s raw (unmultiplied) sizing is sufficient for
/// `prove_ultra_honk` on the real v2.4 bytecode; applying the `* 8` margin
/// here was inflating peak on-device RSS by up to 8x for no benefit (it
/// pushed v2.4 into a dyadic SRS bucket several sizes above what `bb gates`
/// says the circuit actually needs — see docs/M3_findings.md).
///
/// Returns `num_srs_points`.
Future<int> initSrs({required String circuitBytecode, String? srsPath}) =>
    RustLib.instance.api.crateApiProverInitSrs(
      circuitBytecode: circuitBytecode,
      srsPath: srsPath,
    );

/// Like `init_srs`, but with a persistent on-disk cache at `cache_path`: if
/// a valid cache file already exists there, read it (no network -- this is
/// what makes the second and subsequent inscription on a device work
/// offline); otherwise download from crs.aztec.network and write the cache
/// file for next time. `cache_path` should be a device-local, app-owned
/// file path (Dart side: `path_provider`'s `getApplicationSupportDirectory()`
/// joined with a fixed filename) -- not the bundled-VK asset path, and not
/// the bare directory.
///
/// Network/disk failures (no connection, corrupt cache file) are reported
/// as `Err(message)`, never as an unrecovered panic: noir_rs's
/// `NetSrs`/`LocalSrs` call `.unwrap()` internally on the HTTP response and
/// the file read, which would otherwise abort the whole process rather than
/// letting the caller (and ultimately the player, via a normal error
/// dialog) see what went wrong.
///
/// Uses the same unmultiplied sizing as `init_srs` (bundled-VK flow -- see
/// that function's doc comment for why no `* 12` margin here).
Future<int> initSrsCached({
  required String circuitBytecode,
  required String cachePath,
}) => RustLib.instance.api.crateApiProverInitSrsCached(
  circuitBytecode: circuitBytecode,
  cachePath: cachePath,
);

/// Compute the UltraHonk VK (poseidon2 oracle).
///
/// Re-pushes the cached SRS to barretenberg on the current thread first.
/// Requires a prior `init_srs_and_compute_vk` call to have populated the cache.
Future<Uint8List> computeVk({
  required String circuitBytecode,
  required bool lowMemory,
}) => RustLib.instance.api.crateApiProverComputeVk(
  circuitBytecode: circuitBytecode,
  lowMemory: lowMemory,
);

/// Diagnostic: compute VK with Keccak oracle hash (not for production proving).
///
/// Used to test whether "Backend error: vector" is poseidon2-specific (lookup
/// table sizing bug) or a deeper VK computation issue.  If this succeeds while
/// `compute_vk` fails, the bug is in barretenberg's poseidon2 selector/lookup
/// table path on AArch64.
Future<Uint8List> computeVkKeccak({
  required String circuitBytecode,
  required bool lowMemory,
}) => RustLib.instance.api.crateApiProverComputeVkKeccak(
  circuitBytecode: circuitBytecode,
  lowMemory: lowMemory,
);

/// Prove the v2.4 CA circuit and return timing data.
///
/// `circuit_bytecode`     — base64-encoded ACIR bytecode.
/// `grid_state`           — 469 cell values (0 or 1), flat q×r order.
/// `key_hi_hex`/`key_lo_hex` — hex-encoded Field, the Ed25519-key-half pair
///                          (interim zero keys until the identity module lands).
/// `t_hex`                — hex-encoded Field, `1 <= T <= tier_max`.
/// `owner_pubkey_hex`     — hex-encoded Field, `poseidon2_hash2(key_hi, key_lo)`
///                          (CIRCUIT_IO.md CIRCUIT_IO 5/6 — the VK-stable binding).
/// `ruleset_version_hex`  — hex-encoded Field, `RULESET_VERSION`.
/// `vk_bytes`             — from `init_srs_and_compute_vk` or a bundled asset.
/// `low_memory`           — enable file-backed polynomial storage (~2x RAM saving).
///
/// Witness order matches `main()`'s declared parameter order exactly: the 469
/// grid cells, then key_hi, key_lo, T, owner_pubkey, ruleset_version — hex
/// strings throughout (owner_pubkey is a full 254-bit field; u128 cannot
/// represent it, hence `from_vec_str_to_witness_map` rather than the
/// u128-based `from_vec_to_witness_map` the proxy-circuit version used).
///
/// Re-pushes the cached SRS to barretenberg on the current thread (fast, ~5-10 ms,
/// no network).  The cache must be populated by a prior `init_srs_and_compute_vk`.
Future<TimedProofResult> proveAndTime({
  required String circuitBytecode,
  required List<int> gridState,
  required String keyHiHex,
  required String keyLoHex,
  required String tHex,
  required String ownerPubkeyHex,
  required String rulesetVersionHex,
  required List<int> vkBytes,
  required bool lowMemory,
}) => RustLib.instance.api.crateApiProverProveAndTime(
  circuitBytecode: circuitBytecode,
  gridState: gridState,
  keyHiHex: keyHiHex,
  keyLoHex: keyLoHex,
  tHex: tHex,
  ownerPubkeyHex: ownerPubkeyHex,
  rulesetVersionHex: rulesetVersionHex,
  vkBytes: vkBytes,
  lowMemory: lowMemory,
);

/// Verify a proof produced by `prove_and_time`.
Future<bool> verifyProof({
  required List<int> vkBytes,
  required List<int> proofBytes,
}) => RustLib.instance.api.crateApiProverVerifyProof(
  vkBytes: vkBytes,
  proofBytes: proofBytes,
);

/// Extract the `bytecode` base64 string from a Noir circuit JSON artifact.
Future<String> extractBytecode({required String circuitJson}) => RustLib
    .instance
    .api
    .crateApiProverExtractBytecode(circuitJson: circuitJson);

/// Result of a timed prove call.  Returned to Dart; Dart logs wall_ms and
/// peak_rss_kb to logcat so Soren can read them without needing the Profiler.
class TimedProofResult {
  /// Proof bytes in the noir-rs wire format:
  ///   [4 bytes BE: num_public_inputs][public_input fields][proof fields]
  /// Each field is 32 bytes.
  final Uint8List proofBytes;

  /// Wall-clock duration of the prove call, in milliseconds.
  final BigInt wallMs;

  /// Peak resident set size at end of prove call, in KB (Linux /proc/self/status VmHWM).
  /// Returns 0 on platforms that don't expose /proc (iOS simulator, etc.).
  final BigInt peakRssKb;

  const TimedProofResult({
    required this.proofBytes,
    required this.wallMs,
    required this.peakRssKb,
  });

  @override
  int get hashCode =>
      proofBytes.hashCode ^ wallMs.hashCode ^ peakRssKb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimedProofResult &&
          runtimeType == other.runtimeType &&
          proofBytes == other.proofBytes &&
          wallMs == other.wallMs &&
          peakRssKb == other.peakRssKb;
}
