// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate with: python3 scripts/build_avatar_pack.py
//
// The shipped wizard-avatar catalog: one row per character in
// assets/art_pack/avatars/avatar_atlas.png (432x1152), with a
// matching portrait cell in assets/art_pack/avatars/avatar_portraits.png
// (576x864) at the same col/row. Art provenance and
// licence are recorded in assets/art_pack/avatars/ATTRIBUTION.md.

part of 'avatar_sprites.dart';

/// Atlas dimensions, for the source-rect maths in [AvatarAtlas].
const int kAvatarAtlasWidth = 432;
const int kAvatarAtlasHeight = 1152;

/// Portrait atlas dimensions, for the source-rect maths in [AvatarPortraitAtlas].
const int kAvatarPortraitAtlasWidth = 576;
const int kAvatarPortraitAtlasHeight = 864;

/// Every avatar shipped in the pack, in stable catalog order. Ids are stable
/// across regeneration and are what a player's avatar choice is persisted as —
/// never renumber or rename one without a migration.
const List<AvatarArt> kAvatarCatalog = [
  AvatarArt(
    id: 'fighter_f_01',
    name: 'Fighter F 01',
    category: AvatarCategory.heroes,
    atlasCol: 0,
    atlasRow: 0,
    portraitCol: 0,
    portraitRow: 0,
  ),
  AvatarArt(
    id: 'fighter_f_02',
    name: 'Fighter F 02',
    category: AvatarCategory.heroes,
    atlasCol: 1,
    atlasRow: 0,
    portraitCol: 1,
    portraitRow: 0,
  ),
  AvatarArt(
    id: 'fighter_m_01',
    name: 'Fighter M 01',
    category: AvatarCategory.heroes,
    atlasCol: 2,
    atlasRow: 0,
    portraitCol: 2,
    portraitRow: 0,
  ),
  AvatarArt(
    id: 'fighter_m_02',
    name: 'Fighter M 02',
    category: AvatarCategory.heroes,
    atlasCol: 3,
    atlasRow: 0,
    portraitCol: 3,
    portraitRow: 0,
  ),
  AvatarArt(
    id: 'healer_f_01',
    name: 'Healer F 01',
    category: AvatarCategory.heroes,
    atlasCol: 4,
    atlasRow: 0,
    portraitCol: 4,
    portraitRow: 0,
  ),
  AvatarArt(
    id: 'healer_m_01',
    name: 'Healer M 01',
    category: AvatarCategory.heroes,
    atlasCol: 5,
    atlasRow: 0,
    portraitCol: 5,
    portraitRow: 0,
  ),
  AvatarArt(
    id: 'mage_f_01',
    name: 'Mage F 01',
    category: AvatarCategory.heroes,
    atlasCol: 0,
    atlasRow: 1,
    portraitCol: 0,
    portraitRow: 1,
  ),
  AvatarArt(
    id: 'mage_m_01',
    name: 'Mage M 01',
    category: AvatarCategory.heroes,
    atlasCol: 1,
    atlasRow: 1,
    portraitCol: 1,
    portraitRow: 1,
  ),
  AvatarArt(
    id: 'ranger_f_01',
    name: 'Ranger F 01',
    category: AvatarCategory.heroes,
    atlasCol: 2,
    atlasRow: 1,
    portraitCol: 2,
    portraitRow: 1,
  ),
  AvatarArt(
    id: 'ranger_m_01',
    name: 'Ranger M 01',
    category: AvatarCategory.heroes,
    atlasCol: 3,
    atlasRow: 1,
    portraitCol: 3,
    portraitRow: 1,
  ),
  AvatarArt(
    id: 'aristocrate_f_01',
    name: 'Aristocrate F 01',
    category: AvatarCategory.npc,
    atlasCol: 4,
    atlasRow: 1,
    portraitCol: 4,
    portraitRow: 1,
  ),
  AvatarArt(
    id: 'aristocrate_f_02',
    name: 'Aristocrate F 02',
    category: AvatarCategory.npc,
    atlasCol: 5,
    atlasRow: 1,
    portraitCol: 5,
    portraitRow: 1,
  ),
  AvatarArt(
    id: 'aristocrate_f_03',
    name: 'Aristocrate F 03',
    category: AvatarCategory.npc,
    atlasCol: 0,
    atlasRow: 2,
    portraitCol: 0,
    portraitRow: 2,
  ),
  AvatarArt(
    id: 'bard_m_01',
    name: 'Bard M 01',
    category: AvatarCategory.npc,
    atlasCol: 1,
    atlasRow: 2,
    portraitCol: 1,
    portraitRow: 2,
  ),
  AvatarArt(
    id: 'clown_01',
    name: 'Clown 01',
    category: AvatarCategory.npc,
    atlasCol: 2,
    atlasRow: 2,
    portraitCol: 2,
    portraitRow: 2,
  ),
  AvatarArt(
    id: 'cultist_01',
    name: 'Cultist 01',
    category: AvatarCategory.npc,
    atlasCol: 3,
    atlasRow: 2,
    portraitCol: 3,
    portraitRow: 2,
  ),
  AvatarArt(
    id: 'dancer_f_01',
    name: 'Dancer F 01',
    category: AvatarCategory.npc,
    atlasCol: 4,
    atlasRow: 2,
    portraitCol: 4,
    portraitRow: 2,
  ),
  AvatarArt(
    id: 'king_01',
    name: 'King 01',
    category: AvatarCategory.npc,
    atlasCol: 5,
    atlasRow: 2,
    portraitCol: 5,
    portraitRow: 2,
  ),
  AvatarArt(
    id: 'mask_m_01',
    name: 'Mask M 01',
    category: AvatarCategory.npc,
    atlasCol: 0,
    atlasRow: 3,
    portraitCol: 0,
    portraitRow: 3,
  ),
  AvatarArt(
    id: 'npc_f_amanda',
    name: 'NPC F Amanda',
    category: AvatarCategory.npc,
    atlasCol: 1,
    atlasRow: 3,
    portraitCol: 1,
    portraitRow: 3,
  ),
  AvatarArt(
    id: 'pirate_f_01',
    name: 'Pirate F 01',
    category: AvatarCategory.npc,
    atlasCol: 2,
    atlasRow: 3,
    portraitCol: 2,
    portraitRow: 3,
  ),
  AvatarArt(
    id: 'prince_01',
    name: 'Prince 01',
    category: AvatarCategory.npc,
    atlasCol: 3,
    atlasRow: 3,
    portraitCol: 3,
    portraitRow: 3,
  ),
  AvatarArt(
    id: 'princess_01',
    name: 'Princess 01',
    category: AvatarCategory.npc,
    atlasCol: 4,
    atlasRow: 3,
    portraitCol: 4,
    portraitRow: 3,
  ),
  AvatarArt(
    id: 'snow_m_01',
    name: 'Snow M 01',
    category: AvatarCategory.npc,
    atlasCol: 5,
    atlasRow: 3,
    portraitCol: 5,
    portraitRow: 3,
  ),
  AvatarArt(
    id: 'townfolk_adult_f_001',
    name: 'Townfolk Adult F 001',
    category: AvatarCategory.npc,
    atlasCol: 0,
    atlasRow: 4,
    portraitCol: 0,
    portraitRow: 4,
  ),
  AvatarArt(
    id: 'townfolk_adult_f_002',
    name: 'Townfolk Adult F 002',
    category: AvatarCategory.npc,
    atlasCol: 1,
    atlasRow: 4,
    portraitCol: 1,
    portraitRow: 4,
  ),
  AvatarArt(
    id: 'townfolk_adult_f_003',
    name: 'Townfolk Adult F 003',
    category: AvatarCategory.npc,
    atlasCol: 2,
    atlasRow: 4,
    portraitCol: 2,
    portraitRow: 4,
  ),
  AvatarArt(
    id: 'townfolk_adult_f_004',
    name: 'Townfolk Adult F 004',
    category: AvatarCategory.npc,
    atlasCol: 3,
    atlasRow: 4,
    portraitCol: 3,
    portraitRow: 4,
  ),
  AvatarArt(
    id: 'townfolk_adult_f_005',
    name: 'Townfolk Adult F 005',
    category: AvatarCategory.npc,
    atlasCol: 4,
    atlasRow: 4,
    portraitCol: 4,
    portraitRow: 4,
  ),
  AvatarArt(
    id: 'townfolk_adult_f_006',
    name: 'Townfolk Adult F 006',
    category: AvatarCategory.npc,
    atlasCol: 5,
    atlasRow: 4,
    portraitCol: 5,
    portraitRow: 4,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_001',
    name: 'Townfolk Adult M 001',
    category: AvatarCategory.npc,
    atlasCol: 0,
    atlasRow: 5,
    portraitCol: 0,
    portraitRow: 5,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_002',
    name: 'Townfolk Adult M 002',
    category: AvatarCategory.npc,
    atlasCol: 1,
    atlasRow: 5,
    portraitCol: 1,
    portraitRow: 5,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_003',
    name: 'Townfolk Adult M 003',
    category: AvatarCategory.npc,
    atlasCol: 2,
    atlasRow: 5,
    portraitCol: 2,
    portraitRow: 5,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_004',
    name: 'Townfolk Adult M 004',
    category: AvatarCategory.npc,
    atlasCol: 3,
    atlasRow: 5,
    portraitCol: 3,
    portraitRow: 5,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_005',
    name: 'Townfolk Adult M 005',
    category: AvatarCategory.npc,
    atlasCol: 4,
    atlasRow: 5,
    portraitCol: 4,
    portraitRow: 5,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_006',
    name: 'Townfolk Adult M 006',
    category: AvatarCategory.npc,
    atlasCol: 5,
    atlasRow: 5,
    portraitCol: 5,
    portraitRow: 5,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_007',
    name: 'Townfolk Adult M 007',
    category: AvatarCategory.npc,
    atlasCol: 0,
    atlasRow: 6,
    portraitCol: 0,
    portraitRow: 6,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_008',
    name: 'Townfolk Adult M 008',
    category: AvatarCategory.npc,
    atlasCol: 1,
    atlasRow: 6,
    portraitCol: 1,
    portraitRow: 6,
  ),
  AvatarArt(
    id: 'townfolk_adult_m_009',
    name: 'Townfolk Adult M 009',
    category: AvatarCategory.npc,
    atlasCol: 2,
    atlasRow: 6,
    portraitCol: 2,
    portraitRow: 6,
  ),
  AvatarArt(
    id: 'townfolk_child_f_001',
    name: 'Townfolk Child F 001',
    category: AvatarCategory.npc,
    atlasCol: 3,
    atlasRow: 6,
    portraitCol: 3,
    portraitRow: 6,
  ),
  AvatarArt(
    id: 'townfolk_child_f_002',
    name: 'Townfolk Child F 002',
    category: AvatarCategory.npc,
    atlasCol: 4,
    atlasRow: 6,
    portraitCol: 4,
    portraitRow: 6,
  ),
  AvatarArt(
    id: 'townfolk_child_m_001',
    name: 'Townfolk Child M 001',
    category: AvatarCategory.npc,
    atlasCol: 5,
    atlasRow: 6,
    portraitCol: 5,
    portraitRow: 6,
  ),
  AvatarArt(
    id: 'townfolk_child_m_002',
    name: 'Townfolk Child M 002',
    category: AvatarCategory.npc,
    atlasCol: 0,
    atlasRow: 7,
    portraitCol: 0,
    portraitRow: 7,
  ),
  AvatarArt(
    id: 'townfolk_old_f_001',
    name: 'Townfolk Old F 001',
    category: AvatarCategory.npc,
    atlasCol: 1,
    atlasRow: 7,
    portraitCol: 1,
    portraitRow: 7,
  ),
  AvatarArt(
    id: 'townfolk_old_m_001',
    name: 'Townfolk Old M 001',
    category: AvatarCategory.npc,
    atlasCol: 2,
    atlasRow: 7,
    portraitCol: 2,
    portraitRow: 7,
  ),
  AvatarArt(
    id: 'townfolk_old_m_002',
    name: 'Townfolk Old M 002',
    category: AvatarCategory.npc,
    atlasCol: 3,
    atlasRow: 7,
    portraitCol: 3,
    portraitRow: 7,
  ),
  AvatarArt(
    id: 'flower_01',
    name: 'Flower 01',
    category: AvatarCategory.monsters,
    atlasCol: 4,
    atlasRow: 7,
    portraitCol: 4,
    portraitRow: 7,
  ),
  AvatarArt(
    id: 'grassspirit_01',
    name: 'GrassSpirit 01',
    category: AvatarCategory.monsters,
    atlasCol: 5,
    atlasRow: 7,
    portraitCol: 5,
    portraitRow: 7,
  ),
  AvatarArt(
    id: 'mermaid_01',
    name: 'Mermaid 01',
    category: AvatarCategory.monsters,
    atlasCol: 0,
    atlasRow: 8,
    portraitCol: 0,
    portraitRow: 8,
  ),
  AvatarArt(
    id: 'mushroom_01',
    name: 'Mushroom 01',
    category: AvatarCategory.monsters,
    atlasCol: 1,
    atlasRow: 8,
    portraitCol: 1,
    portraitRow: 8,
  ),
  AvatarArt(
    id: 'poprigunchik_01',
    name: 'Poprigunchik 01',
    category: AvatarCategory.monsters,
    atlasCol: 2,
    atlasRow: 8,
    portraitCol: 2,
    portraitRow: 8,
  ),
  AvatarArt(
    id: 'seed_01',
    name: 'Seed 01',
    category: AvatarCategory.monsters,
    atlasCol: 3,
    atlasRow: 8,
    portraitCol: 3,
    portraitRow: 8,
  ),
  AvatarArt(
    id: 'shrump_01',
    name: 'Shrump 01',
    category: AvatarCategory.monsters,
    atlasCol: 4,
    atlasRow: 8,
    portraitCol: 4,
    portraitRow: 8,
  ),
];
