// SPDX-License-Identifier: GPL-3.0-or-later
//
// match_replay.dart — a golden-transcript harness for the battle engine.
//
// ## Why this exists
//
// `turn_loop.dart` is ~7.7k lines and mixes deterministic resolution with
// network sequencing and trust validation. Separating those is the highest-
// value refactor available (see the August 2026 architecture review §5), and
// it is also the most dangerous one in the codebase: the failure mode is a
// subtle reordering that silently breaks lockstep determinism, and the only
// tripwire in production is a state-hash mismatch on someone's phone
// mid-match.
//
// This harness is the safety net that makes that refactor routine. It is the
// same discipline `GOLDEN_VECTORS.md` mandates for the circuit, pointed at the
// battle engine: **the corpus is generated by running the current
// implementation, and any change must reproduce it byte-for-byte.**
//
// ## What a transcript records, and why it is hashes rather than state
//
// Serialising the whole `BattleState` would be a large, brittle artifact that
// every new field silently invalidates. It is also unnecessary. What a
// refactor must preserve is the *observable behaviour* of a turn, and
// `BattleState.toCanonicalBytes()` is already the project's definition of
// that — it is what the two devices hash at each other to agree they are still
// in the same match.
//
// So each turn records:
//
//   * the canonical state hash **on both devices** — authoritative. Both,
//     not one, because a refactor that desynced the two would otherwise pass.
//   * a small readable summary (hp, mana, chain, entity counts) — diagnostic
//     only, never authoritative.
//
// The summary is what makes a broken golden useful. A bare hash tells you
// "turn 3 differs" and nothing else; the summary tells you *which field
// moved*, which is usually the whole diagnosis.
//
// ## What it exercises that a single-turn test cannot
//
// Scripts run several turns against the same pair of loops, so they cover the
// state that lives *between* turns and is deliberately excluded from the
// canonical hash — `_drawSchedules`, `_drawSeedNonce`, `_seenPeerCommitments`,
// `_ripplingNonce`, `_componentStartSeat`, and `PendingDelayedSpell`'s
// non-canonical fields. That set is exactly the "latent divergence" the
// architecture review flags in §7: two clients can hold identical canonical
// hashes while differing in secondary state that steers a later turn. A
// multi-turn transcript is the cheapest thing that can catch it.

import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:crypto/crypto.dart' show sha256;
import 'package:rune_duel/battle/engine/book_commitment.dart';
import 'package:rune_duel/battle/engine/draw_schedule.dart';
import 'package:rune_duel/battle/engine/turn_loop.dart';
import 'package:rune_duel/battle/models/battle_state.dart';
import 'package:rune_duel/battle/models/certified_armor.dart';
import 'package:rune_duel/engine/border_zone.dart';
import 'package:rune_duel/spells/spell_asset.dart';

import '../engine/certified_cast_fixture.dart';
import '../engine/turn_session_pair.dart';

/// One turn's inputs, from both sides. Everything a turn consumes must come
/// from here or from the script's initial state — a script that reaches for
/// wall-clock time, `Random()`, or ambient I/O is not replayable and the
/// harness cannot help you.
class ScriptedTurn {
  const ScriptedTurn({required this.local, required this.peer, this.note});

  /// Fixed inputs, for turns that do not depend on live state.
  factory ScriptedTurn.fixed({
    required TurnInput local,
    required TurnInput peer,
    String? note,
  }) =>
      ScriptedTurn(local: (_) => local, peer: (_) => peer, note: note);

  /// player_a's input, built from its own loop at the moment the turn runs.
  ///
  /// A builder rather than a value because some inputs cannot be known when
  /// the script is written: casting from a dealt hand means naming the card
  /// currently in a slot, and the deal has not happened yet. A script that
  /// hardcoded the answer would be pinning the deal instead of the refill.
  ///
  /// Determinism is preserved because the builder is a pure function of state
  /// the harness already controls — it reads the loop, never a clock or an
  /// unseeded RNG.
  final TurnInput Function(TurnLoop loop) local;

  /// player_b's input, likewise.
  final TurnInput Function(TurnLoop loop) peer;

  /// Human note, carried into the golden file so a reader can follow the
  /// story without reading the script source.
  final String? note;
}

/// A deterministic scripted match: a starting position and a fixed sequence of
/// turns for both players.
class MatchScript {
  const MatchScript({
    required this.name,
    required this.description,
    required this.turns,
    this.localChapterCommitments = const [],
    this.peerChapterCommitments = const [],
    this.localChapter,
    this.peerChapter,
    this.bookmarks = 0,
    this.startBattle = false,
    this.localCharms = const [],
    this.peerCharms = const [],
    this.startingMana = kStartMana,
    this.localArmor,
    this.peerArmor,
    this.localMeleePicker,
    this.peerMeleePicker,
  });

  /// Stable identifier; also the golden file's basename.
  final String name;

  /// What this script is meant to cover. Recorded in the golden so the corpus
  /// documents its own coverage.
  final String description;

  final List<ScriptedTurn> turns;

  /// Grids each side is allowed to cast (the chapter/book membership check).
  ///
  /// Ignored when [localChapter] / [peerChapter] are supplied — the full
  /// chapter implies its own commitment list, and keeping two sources of truth
  /// for the same thing is how they drift apart.
  final List<String> localChapterCommitments;
  final List<String> peerChapterCommitments;

  /// Full chapter contents, when the script needs the draw machinery.
  ///
  /// Supplying these turns on the parts of the engine that only exist once a
  /// player has a deck: the opening deal, hand refill on cast, and the public
  /// per-player [DrawSchedule] both devices maintain for each other. Leave
  /// null for scripts that only care about resolution — a chapter also brings
  /// Merkle book-membership proving with it, which is a different subsystem.
  final List<SpellAsset>? localChapter;
  final List<SpellAsset>? peerChapter;

  /// Bookmarks per wizard, which set hand size (`handSize == bookmarks + 1`).
  final int bookmarks;

  /// Run the battle-start entropy exchange before turn 1.
  ///
  /// Production always does this: it deals the opening hands and picks the
  /// component start seat, so turn 1 is fully castable
  /// (SPELL_DRAW_WIRING_PLAN.md §3). Headless callers that skip it fall back to
  /// dealing from turn-1 entropy, which leaves turn 1 unable to cast from hand.
  ///
  /// Off by default only because turning it on for the existing scripts would
  /// change their goldens for no gain — they have no chapters to deal.
  final bool startBattle;

  /// Counter-charm trajectories each wizard carries into the match.
  ///
  /// A charm fires on any cast — by either side, including its own owner —
  /// whose certified element sequence OPENS with the charm's trajectory.
  final List<List<BorderZone>> localCharms;
  final List<List<BorderZone>> peerCharms;

  /// Opening mana for both wizards (see [makeDuelState]). Only lowered by
  /// scripts about affordability; the default keeps every other golden
  /// byte-identical.
  final int startingMana;

  /// Already-certified Aetherial Armor worn by each wizard, or null for none
  /// (engine v6).
  ///
  /// Equipment, not a derivation: the script hands over a [CertifiedArmor] the
  /// same way `buildDuelBattleState` receives one from duel setup, and the
  /// harness never parses or verifies anything. Earth's HP bonus is folded
  /// into starting HP by [makeDuelState], so an armored script's very first
  /// state hash already differs from an unarmored one — which is exactly the
  /// property a transcript should pin.
  final CertifiedArmor? localArmor;
  final CertifiedArmor? peerArmor;

  /// What each side does in the Phase-4b melee round, or null to never punch.
  ///
  /// A picker rather than a per-turn input because melee is not part of
  /// [TurnInput] — it is its own commit-reveal round, asked of the UI only
  /// when a target exists. `(c) async => c.first` is the deterministic "always
  /// punch" answer: candidates come out of `hexNeighbors` in a fixed order.
  final MeleeTargetPicker? localMeleePicker;
  final MeleeTargetPicker? peerMeleePicker;
}

/// One turn's recorded outcome.
class TurnRecord {
  const TurnRecord({
    required this.turn,
    required this.localStateHash,
    required this.peerStateHash,
    required this.summary,
    required this.events,
    this.drawState = const {},
    this.counters = const [],
    this.note,
  });

  final int turn;

  /// SHA-256 of `toCanonicalBytes()` on each device. **The authoritative
  /// values.** They must equal each other (lockstep) and must equal the
  /// golden (no behaviour change).
  final String localStateHash;
  final String peerStateHash;

  /// Readable scalars, for diagnosis only. Never compared as authority — a
  /// mismatch here that leaves the hashes intact means the summary extractor
  /// changed, not the engine.
  final Map<String, Object?> summary;

  /// Per-type counts of the events this turn emitted.
  ///
  /// Events are NOT in `toCanonicalBytes()` — they drive UI playback, not
  /// consensus — so the state hash cannot see them at all. They are still
  /// observable behaviour a refactor must preserve, and they answer the
  /// question a bare state hash cannot: *did the cast resolve, or fizzle?*
  /// A spell that quietly stops resolving leaves `resolvedSpells` at 0 while
  /// the canonical state looks entirely plausible.
  final Map<String, int> events;

  /// Public per-player draw positions, as **this device** computes them.
  ///
  /// Deliberately recorded even though `_drawSchedules` is NOT in
  /// `toCanonicalBytes()` — that exclusion is the whole point. Draw positions
  /// are publicly recomputable by both clients and steer later turns (which
  /// card a refill hands you), so they are exactly the "two clients hold
  /// identical canonical hashes while differing in secondary state" case the
  /// architecture review flags in §7. The state hash cannot see them; this
  /// can. Omitted from the golden entirely when a script has no chapters, so
  /// resolution-only scripts stay unaffected.
  final Map<String, Object?> drawState;

  /// What the counter charms did this turn, if anything.
  ///
  /// Recorded because a counter is otherwise nearly invisible in a transcript:
  /// a fully-countered cast produces the same *absence* of damage as a cast
  /// that fizzled, was out of range, or never resolved at all. The state hash
  /// proves the two devices agree; only this proves they agree that an
  /// interception is what happened.
  ///
  /// Also carries the charm owner's remaining mana, since a charm charges its
  /// full cost on every trigger regardless of how much it actually cancelled —
  /// the balance rule that makes a long charm a real trade.
  final List<Map<String, Object?>> counters;

  final String? note;

  bool get inLockstep => localStateHash == peerStateHash;

  Map<String, Object?> toJson() => {
        'turn': turn,
        if (note != null) 'note': note,
        'stateHash': localStateHash,
        'events': events,
        if (drawState.isNotEmpty) 'drawState': drawState,
        if (counters.isNotEmpty) 'counters': counters,
        // Recorded separately only when it diverges: an equal pair is the
        // normal case and would double the file for nothing, while an unequal
        // pair is a failure worth shouting about in the artifact itself.
        if (!inLockstep) 'peerStateHashDIVERGED': peerStateHash,
        'summary': summary,
      };
}

/// How a match ended early, when it did.
///
/// ## Why this is not a [TurnRecord]
///
/// A forfeit is the one outcome the canonical state cannot express. Every
/// forfeit condition in the engine is **one-sided by construction**: the
/// device that detects the violation calls `session.sendForfeit(reason)` and
/// then throws, while the offending device — which by definition thinks its
/// own cast was fine — sails on into the next exchange and blocks there
/// forever. Production tears the match down at that point
/// (`battle_screen.dart`'s `peerForfeit` handler); nothing resumes it.
///
/// So there are three things a transcript must say that no state hash can:
///
///   * **which side detected it and which side offended.** Both devices are
///     running the same code; a bug that made the wrong side forfeit would
///     leave every canonical byte plausible.
///   * **the reason tag.** These strings are a wire contract — the peer's UI
///     switches on them (`_forfeitExplanation`) — so a renamed tag is a real
///     behaviour change, not a refactor.
///   * **that the turn aborted before resolving anything**, and that no later
///     turn ran at all.
///
/// The offending device's state is deliberately NOT recorded. Its loop is
/// abandoned mid-turn with no defined stopping point, so whatever it holds is
/// an artifact of where it happened to block, not an observable the engine
/// promises. Recording it would pin scheduling, not behaviour.
class TerminalRecord {
  const TerminalRecord({
    required this.turn,
    required this.reason,
    required this.detectedBy,
    required this.offender,
    required this.error,
    required this.detectorStateHash,
    required this.detectorStateUnchangedApartFromTurnCounter,
    required this.detectorSummary,
    required this.detectorEvents,
    required this.turnsNotRun,
    this.note,
  });

  /// The turn on which the match ended. 1-based, matching [TurnRecord.turn] —
  /// this turn has NO TurnRecord, because it never completed.
  final int turn;

  /// The tag passed to `sendForfeit` (e.g. `unbacked_enhancement_claim`).
  final String reason;

  /// The player whose device rejected the turn and sent the forfeit frame.
  final String detectedBy;

  /// The player whose action was rejected.
  final String offender;

  /// The `StateError` the detecting device threw, verbatim. Carries the
  /// specific commitment, which is what makes a broken golden diagnosable.
  final String error;

  final String detectorStateHash;

  /// True when the detecting device's canonical state is byte-identical to
  /// its state at the end of the previous turn, apart from the turn counter.
  ///
  /// This is the load-bearing check for "the turn aborted before resolving
  /// anything". `runTurn` increments `state.turnNumber` on its very first
  /// line and `toCanonicalBytes` writes it as the leading uint32, so a bare
  /// hash comparison would always differ and prove nothing; skipping those
  /// four bytes asks the question actually worth asking. If a future change
  /// ever let a forfeit land *after* partial resolution, this flips to false.
  final bool detectorStateUnchangedApartFromTurnCounter;

  final Map<String, Object?> detectorSummary;

  /// Events on the detecting device for the aborted turn. `resolvedSpells: 0`
  /// is the direct statement that the offending cast never took effect.
  final Map<String, int> detectorEvents;

  /// Scripted turns after [turn] that were never run, because the match was
  /// over. Must be > 0 for the script to prove anything about later turns —
  /// a forfeit on the final turn cannot distinguish "stopped" from "finished".
  final int turnsNotRun;

  final String? note;

  Map<String, Object?> toJson() => {
        'turn': turn,
        if (note != null) 'note': note,
        'reason': reason,
        'detectedBy': detectedBy,
        'offender': offender,
        'error': error,
        'detectorStateHash': detectorStateHash,
        'detectorStateUnchangedApartFromTurnCounter':
            detectorStateUnchangedApartFromTurnCounter,
        'detectorEvents': detectorEvents,
        'turnsNotRun': turnsNotRun,
        'detectorSummary': detectorSummary,
      };
}

/// A whole scripted match's recorded outcome.
class MatchTranscript {
  const MatchTranscript({
    required this.script,
    required this.records,
    this.terminal,
  });

  final MatchScript script;
  final List<TurnRecord> records;

  /// Set when the match ended early on a forfeit. Null for a script that ran
  /// every turn to completion.
  final TerminalRecord? terminal;

  Map<String, Object?> toJson() => {
        'name': script.name,
        'description': script.description,
        'turns': [for (final r in records) r.toJson()],
        if (terminal != null) 'terminal': terminal!.toJson(),
      };

  String toPrettyJson() =>
      '${const JsonEncoder.withIndent('  ').convert(toJson())}\n';
}

/// A deterministic stand-in for `Random.secure()`, so a transcript replays.
///
/// Commit-reveal salts are the one genuinely random input a turn takes, and
/// they are load-bearing for determinism far beyond the commit itself: the
/// action-phase RNG is seeded from `myCommit ^ peerCommit`, so entity ids,
/// tie-breaks and percentage rolls all move when the salts do. Both devices
/// exchange the commits and therefore agree with each other within a run —
/// which is why this never showed up as a lockstep failure — but no two runs
/// agreed, so a golden could not be reproduced.
///
/// Counter-based rather than a fixed constant: each call must differ, exactly
/// as real salts do, or distinct commits would collide.
class _ScriptedNonces {
  int _counter = 0;

  Uint8List call(int length) {
    final n = _counter++;
    // Spread the counter across the bytes so successive salts differ
    // throughout, not only in a trailing byte.
    return Uint8List.fromList(
      List.generate(length, (i) => (n * 31 + i * 7 + 11) & 0xFF),
    );
  }
}

/// Runs [script] through two real, paired [TurnLoop]s and records what
/// happened.
///
/// Deliberately uses the same `TurnSessionPair` production-shaped exchange the
/// engine tests use, not `SoloBattleSession`: solo echoes state hashes back to
/// the sender and so cannot see a divergence, which is half of what this
/// harness is for.
Future<MatchTranscript> runMatchScript(MatchScript script) async {
  final localState = makeDuelState(
    bookmarks: script.bookmarks,
    localCharms: script.localCharms,
    peerCharms: script.peerCharms,
    startingMana: script.startingMana,
    localArmor: script.localArmor,
    peerArmor: script.peerArmor,
  );
  // The peer device builds the SAME two wizards from the same certified
  // armors — both sides of a real duel derive one reading of each proof
  // (M4.22) and seat it on the same avatar. Handing the peer state a mirrored
  // pair here would model a bug, not a device.
  final peerState = makeDuelState(
    bookmarks: script.bookmarks,
    localCharms: script.localCharms,
    peerCharms: script.peerCharms,
    startingMana: script.startingMana,
    localArmor: script.localArmor,
    peerArmor: script.peerArmor,
  );

  // Chapters must be sorted by commitmentHex before anything derives positions
  // from them: DrawSchedule positions only line up with BookCommitment's
  // Merkle leaf indices when both sort by the same key
  // (SPELL_DRAW_WIRING_PLAN.md §2 consequence 3). Getting this wrong produces
  // a script that casts a card it does not hold.
  List<SpellAsset>? sortChapter(List<SpellAsset>? c) => c == null
      ? null
      : (List<SpellAsset>.from(c)
        ..sort((a, b) => a.commitmentHex.compareTo(b.commitmentHex)));
  final localChapter = sortChapter(script.localChapter);
  final peerChapter = sortChapter(script.peerChapter);
  List<String> hexes(List<SpellAsset> c) =>
      [for (final s in c) s.commitmentHex];

  // Separate counters per side: the two loops draw independently in
  // production too, and sharing one would couple them in a way real devices
  // are not.
  final localNonces = _ScriptedNonces();
  final peerNonces = _ScriptedNonces();

  final pair = TurnSessionPair();
  final localLoop = TurnLoop(
    state: localState,
    session: pair.sessionA,
    localPlayerId: 'player_a',
    verifyProof: alwaysOk,
    vkBytes: Uint8List(0),
    commitNonceSource: localNonces.call,
    meleeTargetPicker: script.localMeleePicker ?? ((_) async => null),
    peerBookRoot:
        peerChapter == null ? null : BookCommitment.computeRoot(hexes(peerChapter)),
    peerBookLeafCount: peerChapter?.length,
  );
  final peerLoop = TurnLoop(
    state: peerState,
    session: pair.sessionB,
    localPlayerId: 'player_b',
    verifyProof: alwaysOk,
    vkBytes: Uint8List(0),
    commitNonceSource: peerNonces.call,
    meleeTargetPicker: script.peerMeleePicker ?? ((_) async => null),
    // Each side verifies the OTHER's book membership, so the roots cross over.
    peerBookRoot:
        localChapter == null ? null : BookCommitment.computeRoot(hexes(localChapter)),
    peerBookLeafCount: localChapter?.length,
  );
  if (localChapter != null) {
    localLoop
      ..localChapterCommitments = hexes(localChapter)
      ..localChapterSpells = localChapter;
  } else {
    localLoop.localChapterCommitments = script.localChapterCommitments;
  }
  if (peerChapter != null) {
    peerLoop
      ..localChapterCommitments = hexes(peerChapter)
      ..localChapterSpells = peerChapter;
  } else {
    peerLoop.localChapterCommitments = script.peerChapterCommitments;
  }

  // Which side sent a forfeit, latched as it happens.
  //
  // `sendForfeit` on one session completes the OTHER session's `peerForfeit`,
  // so a completion on sessionA's future means player_b was the one who
  // detected the violation and sent the frame.
  String? forfeitReason;
  String? forfeitDetectedBy;
  unawaited(pair.sessionA.peerForfeit.then((r) {
    forfeitReason ??= r;
    forfeitDetectedBy ??= 'player_b';
  }));
  unawaited(pair.sessionB.peerForfeit.then((r) {
    forfeitReason ??= r;
    forfeitDetectedBy ??= 'player_a';
  }));

  if (script.startBattle) {
    // Paired commit-reveal, same shape as a turn's — both sides must run it
    // concurrently or they deadlock waiting on each other.
    await Future.wait([localLoop.startBattle(), peerLoop.startBattle()])
        .timeout(const Duration(seconds: 30));
    pair.reset();
  }

  final records = <TurnRecord>[];
  TerminalRecord? terminal;
  // Canonical bytes at the end of the last COMPLETED turn, per device, so a
  // forfeit can be compared against the position it aborted from.
  var localBefore = localState.toCanonicalBytes();
  var peerBefore = peerState.toCanonicalBytes();

  for (var i = 0; i < script.turns.length; i++) {
    final scripted = script.turns[i];
    if (i > 0) {
      // The pair's exchange slots are one-shot Completers, one set per turn.
      // (startBattle already reset after its own exchange.)
      pair.reset();
    }
    try {
      await Future.wait([
        localLoop.runTurn(scripted.local(localLoop)),
        peerLoop.runTurn(scripted.peer(peerLoop)),
      ], eagerError: true).timeout(const Duration(seconds: 30));
    } on StateError catch (e) {
      // A forfeit. `sendForfeit` runs synchronously just before the throw, so
      // the completer is already completed — but its listener is a microtask,
      // so yield once to let the latch above run before reading it.
      await Future<void>.delayed(Duration.zero);
      final reason = forfeitReason;
      final detectedBy = forfeitDetectedBy;
      if (reason == null || detectedBy == null) {
        // A StateError that is NOT a forfeit is a genuine harness or engine
        // failure — a malformed script, a deadlock, a real crash. Swallowing
        // it as "the match ended" would turn every such bug into a green run.
        rethrow;
      }
      final detectorIsLocal = detectedBy == 'player_a';
      final detectorState = detectorIsLocal ? localState : peerState;
      final detectorLoop = detectorIsLocal ? localLoop : peerLoop;
      final detectorBefore = detectorIsLocal ? localBefore : peerBefore;

      terminal = TerminalRecord(
        turn: i + 1,
        reason: reason,
        detectedBy: detectedBy,
        offender: detectorIsLocal ? 'player_b' : 'player_a',
        error: e.message.toString(),
        detectorStateHash: _hashOf(detectorState),
        detectorStateUnchangedApartFromTurnCounter: _sameApartFromTurnCounter(
          detectorBefore,
          detectorState.toCanonicalBytes(),
        ),
        detectorSummary: summarize(detectorState),
        detectorEvents: eventCounts(detectorLoop),
        turnsNotRun: script.turns.length - (i + 1),
        note: scripted.note,
      );
      // The offending loop is still mid-turn, blocked on an exchange its peer
      // will never reach. Running another turn against it would deadlock, and
      // production would not run one either — the match is over.
      break;
    }

    localBefore = localState.toCanonicalBytes();
    peerBefore = peerState.toCanonicalBytes();

    records.add(TurnRecord(
      turn: i + 1,
      localStateHash: _hashOf(localState),
      peerStateHash: _hashOf(peerState),
      summary: summarize(localState),
      events: eventCounts(localLoop),
      drawState: drawStateOf(localLoop, peerLoop),
      counters: countersOf(localLoop, localState),
      note: scripted.note,
    ));
  }

  return MatchTranscript(
    script: script,
    records: records,
    terminal: terminal,
  );
}

/// Whether two canonical encodings agree on everything except the leading
/// turn-number field.
///
/// `toCanonicalBytes` writes `turnNumber` as its first uint32 and nothing else
/// is fixed-width ahead of it, so dropping four bytes is a complete and exact
/// way to ask "did anything other than the clock move?".
bool _sameApartFromTurnCounter(Uint8List before, Uint8List after) {
  if (before.length != after.length) return false;
  for (var i = 4; i < before.length; i++) {
    if (before[i] != after[i]) return false;
  }
  return true;
}

String _hashOf(BattleState state) =>
    sha256.convert(state.toCanonicalBytes()).toString();

/// Per-type event counts for the turn just resolved.
///
/// Counts rather than full contents: contents would make the golden enormous
/// and would churn on cosmetic field changes, while a count moving from 1 to 0
/// (or 1 to 2) is the signal that actually matters. If a future bug needs
/// event *contents* pinned, add a hash of them beside the count rather than
/// inlining them.
Map<String, int> eventCounts(TurnLoop loop) => {
      'castEvents': loop.lastCastEvents.length,
      'resolvedSpells': loop.lastResolvedSpells.length,
      'counterCharmProcs': loop.lastCounterCharmProcs.length,
      'avatarMoves': loop.lastAvatarMoveEvents.length,
      'minionMoves': loop.lastMinionMoveEvents.length,
      'minionAttacks': loop.lastMinionAttackEvents.length,
      'meleeAttacks': loop.lastMeleeAttackEvents.length,
      'wildMagic': loop.lastWildMagicEvents.length,
      'conveyorChains': loop.lastConveyorChainEvents.length,
    };

/// Counter-charm outcomes for the turn just resolved.
///
/// `counteredFormulas` is the load-bearing number: 0 means no charm matched,
/// a value below the cast's formula count means a PARTIAL counter (the leading
/// formulas were cancelled and the rest still resolved), and a value equal to
/// it means the cast was swallowed whole and `_applySpell` never ran at all.
/// Those three outcomes are behaviourally different and a bare state hash
/// cannot tell them apart.
List<Map<String, Object?>> countersOf(TurnLoop loop, BattleState state) => [
      for (final r in loop.lastResolvedSpells)
        if (r.counteredFormulas > 0 || r.wasCountered)
          {
            'spell': r.spell.name,
            'caster': r.casterId,
            'wasFullyCountered': r.wasCountered,
            'counteredFormulas': r.counteredFormulas,
            'charmOwner': r.counterCharmOwnerId,
            'charmOwnerMana': state.avatars
                .where((a) => a.playerId == r.counterCharmOwnerId)
                .map((a) => a.mana)
                .firstOrNull,
          },
    ];

/// Public draw positions for every player both loops know about.
///
/// Records what the LOCAL device computed, and flags any player whose two
/// devices disagree. That disagreement is invisible to the state hash by
/// design — draw schedules are excluded from `toCanonicalBytes()` — so
/// without this the corpus would happily record a match in which the two
/// clients had silently diverged on which cards each player is holding.
Map<String, Object?> drawStateOf(TurnLoop local, TurnLoop peer) {
  final out = <String, Object?>{};
  for (final playerId in const ['player_a', 'player_b']) {
    final mine = local.drawScheduleFor(playerId);
    if (mine == null) continue;
    final theirs = peer.drawScheduleFor(playerId);
    out[playerId] = {
      'hand': mine.hand,
      'remaining': mine.remaining.length,
      'withered': mine.withered.length,
      if (theirs != null && !_sameSchedule(mine, theirs))
        'DIVERGED_peerView': {
          'hand': theirs.hand,
          'remaining': theirs.remaining.length,
        },
    };
  }
  return out;
}

bool _sameSchedule(DrawSchedule a, DrawSchedule b) =>
    a.hand.join(',') == b.hand.join(',') &&
    a.remaining.length == b.remaining.length &&
    a.withered.length == b.withered.length;

/// The readable half of a record.
///
/// Deliberately shallow and stable: fields whose *meaning* is obvious to a
/// human reading a diff. Anything subtle belongs in the hash, which already
/// covers everything canonical. Adding a field here changes every golden, so
/// prefer leaving it out unless a real debugging session wanted it.
Map<String, Object?> summarize(BattleState state) => {
      'turnNumber': state.turnNumber,
      'avatars': {
        for (final av in state.avatars)
          av.playerId: {
            'hp': av.hp,
            'mana': av.mana,
            'chain': av.activeChainElement?.name,
            'position': '${av.position.q},${av.position.r}',
            'statuses': av.activeStatusEffects.length,
          },
      },
      'pendingDelayedSpells': state.pendingDelayedSpells.length,
      'minions': state.minions.length,
      'clouds': state.clouds.length,
      'tileEffects': state.tileEffects.length,
      'terrainBarriers': state.terrainBarriers.length,
      'terrainHp': state.terrainHp.length,
      'reflectionLinks': state.reflectionLinks.length,
      'divinationLinks': state.divinationLinks.length,
      'wizardIllusions': state.wizardIllusions.length,
    };
