// SPDX-License-Identifier: GPL-3.0-or-later
//
// match_replay.dart — a golden-transcript harness for the battle engine.
//
// ## Why this exists
//
// `turn_loop.dart` is ~7.7k lines and mixes deterministic resolution with
// network sequencing and trust validation. Separating those is the highest-
// value refactor available (see the August 2026 architecture review §5), and
// it is also the most dangerous one in the codebase: the failure mode is a
// subtle reordering that silently breaks lockstep determinism, and the only
// tripwire in production is a state-hash mismatch on someone's phone
// mid-match.
//
// This harness is the safety net that makes that refactor routine. It is the
// same discipline `GOLDEN_VECTORS.md` mandates for the circuit, pointed at the
// battle engine: **the corpus is generated by running the current
// implementation, and any change must reproduce it byte-for-byte.**
//
// ## What a transcript records, and why it is hashes rather than state
//
// Serialising the whole `BattleState` would be a large, brittle artifact that
// every new field silently invalidates. It is also unnecessary. What a
// refactor must preserve is the *observable behaviour* of a turn, and
// `BattleState.toCanonicalBytes()` is already the project's definition of
// that — it is what the two devices hash at each other to agree they are still
// in the same match.
//
// So each turn records:
//
//   * the canonical state hash **on both devices** — authoritative. Both,
//     not one, because a refactor that desynced the two would otherwise pass.
//   * a small readable summary (hp, mana, chain, entity counts) — diagnostic
//     only, never authoritative.
//
// The summary is what makes a broken golden useful. A bare hash tells you
// "turn 3 differs" and nothing else; the summary tells you *which field
// moved*, which is usually the whole diagnosis.
//
// ## What it exercises that a single-turn test cannot
//
// Scripts run several turns against the same pair of loops, so they cover the
// state that lives *between* turns and is deliberately excluded from the
// canonical hash — `_drawSchedules`, `_drawSeedNonce`, `_seenPeerCommitments`,
// `_ripplingNonce`, `_componentStartSeat`, and `PendingDelayedSpell`'s
// non-canonical fields. That set is exactly the "latent divergence" the
// architecture review flags in §7: two clients can hold identical canonical
// hashes while differing in secondary state that steers a later turn. A
// multi-turn transcript is the cheapest thing that can catch it.

import 'dart:convert';
import 'dart:typed_data';

import 'package:crypto/crypto.dart' show sha256;
import 'package:rune_duel/battle/engine/turn_loop.dart';
import 'package:rune_duel/battle/models/battle_state.dart';

import '../engine/certified_cast_fixture.dart';
import '../engine/turn_session_pair.dart';

/// One turn's inputs, from both sides. Everything a turn consumes must come
/// from here or from the script's initial state — a script that reaches for
/// wall-clock time, `Random()`, or ambient I/O is not replayable and the
/// harness cannot help you.
class ScriptedTurn {
  const ScriptedTurn({required this.local, required this.peer, this.note});

  /// player_a's input (the loop whose `localPlayerId` is `player_a`).
  final TurnInput local;

  /// player_b's input.
  final TurnInput peer;

  /// Human note, carried into the golden file so a reader can follow the
  /// story without reading the script source.
  final String? note;
}

/// A deterministic scripted match: a starting position and a fixed sequence of
/// turns for both players.
class MatchScript {
  const MatchScript({
    required this.name,
    required this.description,
    required this.turns,
    this.localChapterCommitments = const [],
    this.peerChapterCommitments = const [],
  });

  /// Stable identifier; also the golden file's basename.
  final String name;

  /// What this script is meant to cover. Recorded in the golden so the corpus
  /// documents its own coverage.
  final String description;

  final List<ScriptedTurn> turns;

  /// Grids each side is allowed to cast (the chapter/book membership check).
  final List<String> localChapterCommitments;
  final List<String> peerChapterCommitments;
}

/// One turn's recorded outcome.
class TurnRecord {
  const TurnRecord({
    required this.turn,
    required this.localStateHash,
    required this.peerStateHash,
    required this.summary,
    required this.events,
    this.note,
  });

  final int turn;

  /// SHA-256 of `toCanonicalBytes()` on each device. **The authoritative
  /// values.** They must equal each other (lockstep) and must equal the
  /// golden (no behaviour change).
  final String localStateHash;
  final String peerStateHash;

  /// Readable scalars, for diagnosis only. Never compared as authority — a
  /// mismatch here that leaves the hashes intact means the summary extractor
  /// changed, not the engine.
  final Map<String, Object?> summary;

  /// Per-type counts of the events this turn emitted.
  ///
  /// Events are NOT in `toCanonicalBytes()` — they drive UI playback, not
  /// consensus — so the state hash cannot see them at all. They are still
  /// observable behaviour a refactor must preserve, and they answer the
  /// question a bare state hash cannot: *did the cast resolve, or fizzle?*
  /// A spell that quietly stops resolving leaves `resolvedSpells` at 0 while
  /// the canonical state looks entirely plausible.
  final Map<String, int> events;

  final String? note;

  bool get inLockstep => localStateHash == peerStateHash;

  Map<String, Object?> toJson() => {
        'turn': turn,
        if (note != null) 'note': note,
        'stateHash': localStateHash,
        'events': events,
        // Recorded separately only when it diverges: an equal pair is the
        // normal case and would double the file for nothing, while an unequal
        // pair is a failure worth shouting about in the artifact itself.
        if (!inLockstep) 'peerStateHashDIVERGED': peerStateHash,
        'summary': summary,
      };
}

/// A whole scripted match's recorded outcome.
class MatchTranscript {
  const MatchTranscript({required this.script, required this.records});

  final MatchScript script;
  final List<TurnRecord> records;

  Map<String, Object?> toJson() => {
        'name': script.name,
        'description': script.description,
        'turns': [for (final r in records) r.toJson()],
      };

  String toPrettyJson() =>
      '${const JsonEncoder.withIndent('  ').convert(toJson())}\n';
}

/// Runs [script] through two real, paired [TurnLoop]s and records what
/// happened.
///
/// Deliberately uses the same `TurnSessionPair` production-shaped exchange the
/// engine tests use, not `SoloBattleSession`: solo echoes state hashes back to
/// the sender and so cannot see a divergence, which is half of what this
/// harness is for.
Future<MatchTranscript> runMatchScript(MatchScript script) async {
  final localState = makeDuelState();
  final peerState = makeDuelState();

  final pair = TurnSessionPair();
  final localLoop = TurnLoop(
    state: localState,
    session: pair.sessionA,
    localPlayerId: 'player_a',
    verifyProof: alwaysOk,
    vkBytes: Uint8List(0),
  );
  final peerLoop = TurnLoop(
    state: peerState,
    session: pair.sessionB,
    localPlayerId: 'player_b',
    verifyProof: alwaysOk,
    vkBytes: Uint8List(0),
  );
  localLoop.localChapterCommitments = script.localChapterCommitments;
  peerLoop.localChapterCommitments = script.peerChapterCommitments;

  final records = <TurnRecord>[];
  for (var i = 0; i < script.turns.length; i++) {
    final scripted = script.turns[i];
    if (i > 0) {
      // The pair's exchange slots are one-shot Completers, one set per turn.
      pair.reset();
    }
    await Future.wait([
      localLoop.runTurn(scripted.local),
      peerLoop.runTurn(scripted.peer),
    ], eagerError: true).timeout(const Duration(seconds: 30));

    records.add(TurnRecord(
      turn: i + 1,
      localStateHash: _hashOf(localState),
      peerStateHash: _hashOf(peerState),
      summary: summarize(localState),
      events: eventCounts(localLoop),
      note: scripted.note,
    ));
  }

  return MatchTranscript(script: script, records: records);
}

String _hashOf(BattleState state) =>
    sha256.convert(state.toCanonicalBytes()).toString();

/// Per-type event counts for the turn just resolved.
///
/// Counts rather than full contents: contents would make the golden enormous
/// and would churn on cosmetic field changes, while a count moving from 1 to 0
/// (or 1 to 2) is the signal that actually matters. If a future bug needs
/// event *contents* pinned, add a hash of them beside the count rather than
/// inlining them.
Map<String, int> eventCounts(TurnLoop loop) => {
      'castEvents': loop.lastCastEvents.length,
      'resolvedSpells': loop.lastResolvedSpells.length,
      'counterCharmProcs': loop.lastCounterCharmProcs.length,
      'avatarMoves': loop.lastAvatarMoveEvents.length,
      'minionMoves': loop.lastMinionMoveEvents.length,
      'minionAttacks': loop.lastMinionAttackEvents.length,
      'meleeAttacks': loop.lastMeleeAttackEvents.length,
      'wildMagic': loop.lastWildMagicEvents.length,
      'conveyorChains': loop.lastConveyorChainEvents.length,
    };

/// The readable half of a record.
///
/// Deliberately shallow and stable: fields whose *meaning* is obvious to a
/// human reading a diff. Anything subtle belongs in the hash, which already
/// covers everything canonical. Adding a field here changes every golden, so
/// prefer leaving it out unless a real debugging session wanted it.
Map<String, Object?> summarize(BattleState state) => {
      'turnNumber': state.turnNumber,
      'avatars': {
        for (final av in state.avatars)
          av.playerId: {
            'hp': av.hp,
            'mana': av.mana,
            'chain': av.activeChainElement?.name,
            'position': '${av.position.q},${av.position.r}',
            'statuses': av.activeStatusEffects.length,
          },
      },
      'pendingDelayedSpells': state.pendingDelayedSpells.length,
      'minions': state.minions.length,
      'clouds': state.clouds.length,
      'tileEffects': state.tileEffects.length,
      'terrainBarriers': state.terrainBarriers.length,
      'terrainHp': state.terrainHp.length,
      'reflectionLinks': state.reflectionLinks.length,
      'divinationLinks': state.divinationLinks.length,
      'wizardIllusions': state.wizardIllusions.length,
    };
